const std = @import("std");
const assert = std.debug.assert;
const stdx = @import("tiger_framework").stdx;
const message = @import("message.zig");
const state_machine = @import("state_machine.zig");

const SM = state_machine.StateMachineType(state_machine.MemoryStorage);

/// Single source of truth for all struct types emitted as TS interfaces.
/// The emit block, is_known_struct, and the uniqueness assertion all
/// derive from this list. Adding a type here is the only step needed.
const known_structs = .{
    // Extern structs
    message.Product,
    message.ProductCollection,
    message.InventoryTransfer,
    message.OrderItem,
    message.OrderRequest,
    message.OrderCompletion,
    message.OrderResultItem,
    message.OrderResult,
    message.OrderSummary,
    message.SearchQuery,
    message.ListParams,
    message.LoginCodeRequest,
    message.LoginVerification,
    message.Message,
    // Flags
    message.ProductFlags,
    message.CollectionFlags,
    // Regular structs
    message.ProductList,
    message.CollectionWithProducts,
    message.CollectionList,
    message.OrderSummaryList,
    message.PageLoadDashboardResult,
    message.LoginResult,
    message.FollowupState,
    message.MessageResponse,
    // SM-internal
    SM.LoginCodeWrite,
    SM.LoginCodeKey,
    SM.ExecuteResult,
};

/// All enum types emitted as TS string literal unions.
const known_enums = .{
    message.Status,
    message.Operation,
    message.OrderStatus,
    message.OrderCompletion.OrderCompletionResult,
    message.ListParams.ActiveFilter,
    message.EventTag,
    state_machine.StorageResult,
    message.MessageResponse.SessionKind,
    message.MessageResponse.SessionAction,
};

/// All union types emitted as TS discriminated unions.
const known_unions = .{
    message.Result,
    SM.Write,
};

const output = blk: {
    @setEvalBranchQuota(100000);
    var buf: [65536]u8 = undefined;
    var w = Writer{ .buf = &buf, .pos = 0 };

    w.raw("// Auto-generated by `zig build codegen` — do not edit.\n\n");

    // --- Constants ---
    w.emit_const("body_max", message.body_max);
    w.emit_const("list_max", message.list_max);
    w.emit_const("dashboard_list_max", message.dashboard_list_max);
    w.emit_const("order_items_max", message.order_items_max);
    w.emit_const("product_name_max", message.product_name_max);
    w.emit_const("product_description_max", message.product_description_max);
    w.emit_const("collection_name_max", message.collection_name_max);
    w.emit_const("search_query_max", message.search_query_max);
    w.emit_const("email_max", message.email_max);
    w.emit_const("code_length", message.code_length);
    w.emit_const("payment_ref_max", message.payment_ref_max);
    w.emit_const("order_timeout_seconds", message.order_timeout_seconds);
    w.emit_const("credential_max", message.Message.credential_max);
    w.emit_const("writes_max", SM.writes_max);
    w.raw("\n");

    // --- Enums ---
    for (known_enums) |T| w.emit_enum(T);

    // --- Structs (dispatch by layout) ---
    for (known_structs) |T| {
        const layout = @typeInfo(T).@"struct".layout;
        if (layout == .@"packed") {
            w.emit_packed_struct(T);
        } else if (layout == .@"extern") {
            w.emit_extern_struct(T);
        } else {
            w.emit_struct(T);
        }
    }

    // --- Anonymous struct interfaces for union variants ---
    for (known_unions) |U| w.emit_union_anon_structs(U);

    // --- Tagged unions ---
    for (known_unions) |U| w.emit_union(U);

    // --- Exhaustiveness assertions ---

    // Union variant counts — if a variant is added, codegen must be updated.
    assert(@typeInfo(message.Result).@"union".fields.len == 10);
    assert(@typeInfo(SM.Write).@"union".fields.len == 11);

    // Anon struct counts — ties emit_union_anon_structs to emit_union.
    assert(count_anon_structs(SM.Write) == 3);
    assert(count_anon_structs(message.Result) == 0);

    // Every Operation.EventType references a type we handle.
    for (@typeInfo(message.Operation).@"enum".fields) |op_field| {
        const op: message.Operation = @enumFromInt(op_field.value);
        const ET = op.EventType();
        if (ET != void) {
            assert(is_known_struct(ET) or @typeInfo(ET) == .int);
        }
    }

    // No two emitted types produce the same TS name.
    assert_no_name_collisions();

    // Buffer headroom — assert we used less than 75% to catch bloat early.
    assert(w.pos > 0);
    assert(w.pos < buf.len * 3 / 4);

    const final = buf[0..w.pos];
    break :blk final[0..final.len].*;
};

pub fn main() !void {
    try std.io.getStdOut().writer().writeAll(&output);
}

// ---------------------------------------------------------------------------
// Writer — comptime string builder
// ---------------------------------------------------------------------------

const Writer = struct {
    buf: *[65536]u8,
    pos: usize,

    fn raw(w: *Writer, s: []const u8) void {
        assert(w.pos + s.len <= w.buf.len);
        @memcpy(w.buf[w.pos..][0..s.len], s);
        w.pos += s.len;
    }

    fn write_pascal(w: *Writer, comptime name: []const u8) void {
        var cap = true;
        for (name) |ch| {
            if (ch == '_') {
                cap = true;
            } else {
                w.buf[w.pos] = if (cap and ch >= 'a' and ch <= 'z') ch - 32 else ch;
                w.pos += 1;
                cap = false;
            }
        }
    }

    fn int(w: *Writer, comptime n: comptime_int) void {
        w.raw(int_str(n));
    }

    // --- Constants ---

    fn emit_const(w: *Writer, comptime name: []const u8, comptime value: comptime_int) void {
        w.raw("export const ");
        w.raw(name);
        w.raw(" = ");
        w.int(value);
        w.raw(";\n");
    }

    // --- Enums ---
    // Name derived from type — no free string parameter.

    fn emit_enum(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const fields = @typeInfo(T).@"enum".fields;
        assert(fields.len > 0);

        w.raw("export type ");
        w.raw(name);
        w.raw(" =\n");
        for (fields) |field| {
            assert(is_ts_identifier(field.name));
            w.raw("  | \"");
            w.raw(field.name);
            w.raw("\"\n");
        }
        w.raw("  ;\n\n");

        w.raw("export const ");
        w.raw(name);
        w.raw("Values = {\n");
        for (fields) |field| {
            w.raw("  ");
            w.raw(field.name);
            w.raw(": ");
            w.int(field.value);
            w.raw(",\n");
        }
        w.raw("} as const;\n\n");
    }

    // --- Packed flag structs ---

    fn emit_packed_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        assert(@typeInfo(T).@"struct".layout == .@"packed");

        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");
        var bool_count: usize = 0;
        for (@typeInfo(T).@"struct".fields) |field| {
            if (std.mem.eql(u8, field.name, "padding")) continue;
            if (field.type != bool) continue;
            bool_count += 1;
            w.raw("  ");
            w.raw(field.name);
            w.raw(": boolean;\n");
        }
        assert(bool_count > 0);
        w.raw("}\n\n");
    }

    // --- Extern structs (with @offset/@size JSDoc) ---

    fn emit_extern_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const info = @typeInfo(T).@"struct";
        assert(info.layout == .@"extern");
        assert(stdx.no_padding(T));

        w.raw("/** @size ");
        w.int(@sizeOf(T));
        w.raw(" */\n");
        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");

        var field_count: usize = 0;
        for (info.fields) |field| {
            if (should_skip(T, field.name)) continue;
            field_count += 1;

            // JSDoc with offset (and @max for arrays with _len companion)
            w.raw("  /** @offset ");
            w.int(@offsetOf(T, field.name));
            if (is_array_type(field.type) and has_len_companion(T, field.name)) {
                w.raw(" @max ");
                w.int(@typeInfo(field.type).array.len);
            }
            w.raw(" */\n");

            w.emit_field_decl(T, field);
        }
        assert(field_count > 0);

        w.raw("}\n\n");
    }

    // --- Regular structs (no offset JSDoc) ---
    // Asserts the type is NOT extern or packed — those have dedicated emit
    // functions. Calling this on an extern struct would silently drop @offset
    // JSDoc that the serde layer depends on.

    fn emit_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const layout = @typeInfo(T).@"struct".layout;
        assert(layout != .@"extern");
        assert(layout != .@"packed");

        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");

        for (@typeInfo(T).@"struct".fields) |field| {
            if (should_skip(T, field.name)) continue;

            if (is_array_type(field.type) and has_len_companion(T, field.name)) {
                w.raw("  /** @max ");
                w.int(@typeInfo(field.type).array.len);
                w.raw(" */\n");
            }

            w.emit_field_decl(T, field);
        }

        w.raw("}\n\n");
    }

    // --- Shared field declaration ---

    fn emit_field_decl(w: *Writer, comptime StructT: type, comptime field: std.builtin.Type.StructField) void {
        w.raw("  ");
        w.raw(field.name);
        w.raw(": ");
        w.write_field_type(StructT, field);
        w.raw(";\n");
    }

    fn write_field_type(w: *Writer, comptime StructT: type, comptime field: std.builtin.Type.StructField) void {
        if (is_array_type(field.type)) {
            const arr = @typeInfo(field.type).array;
            if (arr.child != u8) {
                // [N]T where T != u8 → T[] regardless of _len companion.
                w.write_ts_type(arr.child);
                w.raw("[]");
            } else if (has_len_companion(StructT, field.name)) {
                // [N]u8 with _len → string.
                w.raw("string");
            } else {
                // [N]u8 without _len → Uint8Array.
                w.raw("Uint8Array");
            }
            return;
        }
        w.write_ts_type(field.type);
    }

    fn write_ts_type(w: *Writer, comptime T: type) void {
        switch (@typeInfo(T)) {
            .int => |i| {
                if (i.bits == 128) w.raw("string") else w.raw("number");
            },
            .bool => w.raw("boolean"),
            .void => w.raw("void"),
            .@"enum" => w.raw(type_leaf_name(T)),
            .@"struct" => w.raw(type_leaf_name(T)),
            .@"union" => w.raw(type_leaf_name(T)),
            .optional => |opt| {
                w.write_ts_type(opt.child);
                w.raw(" | null");
            },
            else => @compileError("unhandled type: " ++ @typeName(T)),
        }
    }

    // --- Anonymous struct interfaces for union variants ---

    fn emit_union_anon_structs(w: *Writer, comptime U: type) void {
        const prefix = type_leaf_name(U);
        for (@typeInfo(U).@"union".fields) |field| {
            if (field.type == void) continue;
            if (@typeInfo(field.type) != .@"struct") continue;
            if (is_known_struct(field.type)) continue;

            w.raw("export interface ");
            w.raw(prefix);
            w.write_pascal(field.name);
            w.raw(" {\n");

            for (@typeInfo(field.type).@"struct".fields) |sf| {
                if (should_skip(field.type, sf.name)) continue;

                if (is_array_type(sf.type) and has_len_companion(field.type, sf.name)) {
                    w.raw("  /** @max ");
                    w.int(@typeInfo(sf.type).array.len);
                    w.raw(" */\n");
                }

                w.emit_field_decl(field.type, sf);
            }

            w.raw("}\n\n");
        }
    }

    // --- Tagged unions ---

    fn emit_union(w: *Writer, comptime U: type) void {
        const name = type_leaf_name(U);
        w.raw("export type ");
        w.raw(name);
        w.raw(" =\n");

        for (@typeInfo(U).@"union".fields) |field| {
            w.raw("  | { tag: \"");
            w.raw(field.name);
            w.raw("\"");
            if (field.type != void) {
                w.raw("; value: ");
                w.write_variant_type(U, field.name, field.type);
            }
            w.raw(" }\n");
        }

        w.raw("  ;\n\n");
    }

    /// Variant type reference — delegates to write_ts_type for all known types.
    /// Only overrides the struct branch for anonymous structs, which get a
    /// generated name (union prefix + PascalCase variant name).
    fn write_variant_type(w: *Writer, comptime U: type, comptime variant_name: []const u8, comptime T: type) void {
        if (@typeInfo(T) == .@"struct" and !is_known_struct(T)) {
            w.raw(type_leaf_name(U));
            w.write_pascal(variant_name);
        } else {
            w.write_ts_type(T);
        }
    }
};

// ---------------------------------------------------------------------------
// Comptime helpers
// ---------------------------------------------------------------------------

fn int_str(comptime n: comptime_int) []const u8 {
    if (n == 0) return "0";
    var buf_local: [20]u8 = undefined;
    var pos: usize = 20;
    var val = if (n < 0) -n else n;
    while (val > 0) {
        pos -= 1;
        buf_local[pos] = @intCast('0' + val % 10);
        val = val / 10;
    }
    if (n < 0) {
        pos -= 1;
        buf_local[pos] = '-';
    }
    return buf_local[pos..20];
}

fn type_leaf_name(comptime T: type) []const u8 {
    const full = @typeName(T);
    var last_dot: usize = 0;
    for (full, 0..) |ch, i| {
        if (ch == '.') last_dot = i + 1;
    }
    const name = if (last_dot == 0) full else full[last_dot..];
    assert(name.len > 0);
    assert(is_ts_identifier(name));
    return name;
}

/// Returns true if s is a valid TypeScript identifier (ASCII letters, digits, underscores).
fn is_ts_identifier(comptime s: []const u8) bool {
    if (s.len == 0) return false;
    if (!((s[0] >= 'a' and s[0] <= 'z') or (s[0] >= 'A' and s[0] <= 'Z') or s[0] == '_')) return false;
    for (s[1..]) |ch| {
        if (!((ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z') or (ch >= '0' and ch <= '9') or ch == '_')) return false;
    }
    return true;
}

fn is_array_type(comptime T: type) bool {
    return @typeInfo(T) == .array;
}

fn has_field(comptime StructT: type, comptime name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, name)) return true;
    }
    return false;
}

/// Checks whether `field_name` has a length companion field in StructT.
/// Detects `{name}_len` and the `items` + `len` pattern.
/// Asserts the base field is actually an array — if not, the _len naming
/// convention is misleading and the codegen would produce wrong output.
fn has_len_companion(comptime StructT: type, comptime field_name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (f.name.len == field_name.len + 4 and
            std.mem.eql(u8, f.name[0..field_name.len], field_name) and
            std.mem.eql(u8, f.name[field_name.len..], "_len"))
        {
            assert(is_array_field(StructT, field_name));
            return true;
        }
    }
    if (std.mem.eql(u8, field_name, "items") and has_field(StructT, "len")) {
        assert(is_array_field(StructT, "items"));
        return true;
    }
    return false;
}

/// Returns true if the named field in StructT is an array type.
fn is_array_field(comptime StructT: type, comptime field_name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, field_name)) return is_array_type(f.type);
    }
    return false;
}

/// Returns true if a field should be omitted from the TS output.
fn should_skip(comptime StructT: type, comptime field_name: []const u8) bool {
    if (std.mem.startsWith(u8, field_name, "reserved")) return true;
    if (std.mem.eql(u8, field_name, "padding")) return true;

    // Skip _len companions (e.g., "name_len" when "name" exists)
    if (field_name.len > 4 and std.mem.eql(u8, field_name[field_name.len - 4 ..], "_len")) {
        const base = field_name[0 .. field_name.len - 4];
        if (has_field(StructT, base)) return true;
    }

    // Skip bare "len" when there's an "items" field (list structs)
    if (std.mem.eql(u8, field_name, "len") and has_field(StructT, "items")) return true;

    return false;
}

/// Counts union variants whose type is an anonymous struct (not in is_known_struct).
fn count_anon_structs(comptime U: type) usize {
    var count: usize = 0;
    for (@typeInfo(U).@"union".fields) |field| {
        if (field.type == void) continue;
        if (@typeInfo(field.type) != .@"struct") continue;
        if (!is_known_struct(field.type)) count += 1;
    }
    return count;
}

/// Returns true if T is a struct in the known_structs list.
fn is_known_struct(comptime T: type) bool {
    // 14 extern + 2 flags + 8 regular + 3 SM-internal = 27
    comptime assert(known_structs.len == 27);
    inline for (known_structs) |K| {
        if (T == K) return true;
    }
    return false;
}

/// Returns true if T is an enum in the known_enums list.
fn is_known_enum(comptime T: type) bool {
    comptime assert(known_enums.len == 9);
    inline for (known_enums) |E| {
        if (T == E) return true;
    }
    return false;
}

/// Returns true if T is a union in the known_unions list.
fn is_known_union(comptime T: type) bool {
    comptime assert(known_unions.len == 2);
    inline for (known_unions) |U| {
        if (T == U) return true;
    }
    return false;
}

/// Asserts no two emitted types produce the same TS name.
/// Checks across all categories: enums, structs, unions, anonymous interfaces.
fn assert_no_name_collisions() void {
    @setEvalBranchQuota(200000);
    // Struct leaf names are unique among themselves.
    inline for (known_structs) |K1| {
        var count: usize = 0;
        inline for (known_structs) |K2| {
            if (std.mem.eql(u8, type_leaf_name(K1), type_leaf_name(K2))) count += 1;
        }
        assert(count == 1);
    }

    // Enum leaf names are unique among themselves.
    inline for (known_enums) |E1| {
        var count: usize = 0;
        inline for (known_enums) |E2| {
            if (std.mem.eql(u8, type_leaf_name(E1), type_leaf_name(E2))) count += 1;
        }
        assert(count == 1);
    }

    // No enum name collides with a struct name.
    inline for (known_enums) |E| {
        inline for (known_structs) |S| {
            assert(!std.mem.eql(u8, type_leaf_name(E), type_leaf_name(S)));
        }
    }

    // No union name collides with an enum or struct name.
    inline for (known_unions) |U| {
        inline for (known_enums) |E| {
            assert(!std.mem.eql(u8, type_leaf_name(U), type_leaf_name(E)));
        }
        inline for (known_structs) |S| {
            assert(!std.mem.eql(u8, type_leaf_name(U), type_leaf_name(S)));
        }
    }

    // Every enum/union type referenced as a struct field is in the known lists.
    // If someone adds a new enum to message.zig and uses it in a struct field
    // without adding it to known_enums, this assertion catches it.
    inline for (known_structs) |S| {
        inline for (@typeInfo(S).@"struct".fields) |field| {
            if (@typeInfo(field.type) == .@"enum") {
                assert(is_known_enum(field.type));
            }
            if (@typeInfo(field.type) == .@"union") {
                assert(is_known_union(field.type));
            }
            // Check optional children (e.g., ?FollowupState).
            if (@typeInfo(field.type) == .optional) {
                const child = @typeInfo(field.type).optional.child;
                if (@typeInfo(child) == .@"enum") assert(is_known_enum(child));
                if (@typeInfo(child) == .@"union") assert(is_known_union(child));
            }
        }
    }
}

// =====================================================================
// Tests
// =====================================================================

test "int_str decimal formatting" {
    comptime assert(std.mem.eql(u8, int_str(0), "0"));
    comptime assert(std.mem.eql(u8, int_str(7), "7"));
    comptime assert(std.mem.eql(u8, int_str(42), "42"));
    comptime assert(std.mem.eql(u8, int_str(672), "672"));
    comptime assert(std.mem.eql(u8, int_str(-1), "-1"));
    comptime assert(std.mem.eql(u8, int_str(-60), "-60"));
    comptime assert(std.mem.eql(u8, int_str(message.body_max), "672"));
    comptime assert(std.mem.eql(u8, int_str(message.list_max), "50"));
    comptime assert(std.mem.eql(u8, int_str(SM.writes_max), "21"));
    comptime assert(std.mem.eql(u8, int_str(@sizeOf(message.Message)), "880"));
}

test "should_skip field filtering" {
    // Reserved fields — always skipped.
    comptime assert(should_skip(message.ProductCollection, "reserved"));
    comptime assert(should_skip(message.InventoryTransfer, "reserved"));
    comptime assert(should_skip(message.Message, "reserved"));

    // Padding — always skipped.
    comptime assert(should_skip(message.ProductFlags, "padding"));

    // _len companions — skipped when base field exists.
    comptime assert(should_skip(message.Product, "name_len"));
    comptime assert(should_skip(message.Product, "description_len"));
    comptime assert(should_skip(message.OrderResult, "items_len"));
    comptime assert(should_skip(message.OrderResult, "payment_ref_len"));
    comptime assert(should_skip(message.Message, "credential_len"));

    // Bare "len" — skipped when "items" exists.
    comptime assert(should_skip(message.ProductList, "len"));
    comptime assert(should_skip(message.CollectionList, "len"));
    comptime assert(should_skip(message.OrderSummaryList, "len"));

    // items_len on OrderSummary — NOT a companion (no "items" array field).
    comptime assert(!should_skip(message.OrderSummary, "items_len"));

    // Regular fields — never skipped.
    comptime assert(!should_skip(message.Product, "id"));
    comptime assert(!should_skip(message.Product, "name"));
    comptime assert(!should_skip(message.Product, "price_cents"));
    comptime assert(!should_skip(message.Product, "flags"));
    comptime assert(!should_skip(message.OrderResult, "status"));
    comptime assert(!should_skip(message.Message, "operation"));
    comptime assert(!should_skip(message.Message, "body"));
}

test "has_len_companion detection" {
    // Byte arrays with _len.
    comptime assert(has_len_companion(message.Product, "name"));
    comptime assert(has_len_companion(message.Product, "description"));
    comptime assert(has_len_companion(message.OrderCompletion, "payment_ref"));
    comptime assert(has_len_companion(message.Message, "credential"));
    comptime assert(has_len_companion(message.LoginCodeRequest, "email"));

    // Typed arrays with _len.
    comptime assert(has_len_companion(message.OrderRequest, "items"));
    comptime assert(has_len_companion(message.OrderResult, "items"));

    // items + len pattern (list structs).
    comptime assert(has_len_companion(message.ProductList, "items"));
    comptime assert(has_len_companion(message.CollectionList, "items"));

    // Fields without companions.
    comptime assert(!has_len_companion(message.Product, "id"));
    comptime assert(!has_len_companion(message.Product, "price_cents"));
    comptime assert(!has_len_companion(message.Product, "flags"));
    comptime assert(!has_len_companion(message.Message, "body"));
    comptime assert(!has_len_companion(message.LoginVerification, "code"));
}

test "type_leaf_name extracts last segment" {
    // Simple module-qualified names.
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Product), "Product"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Status), "Status"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Operation), "Operation"));

    // Nested types (enum inside struct).
    comptime assert(std.mem.eql(u8, type_leaf_name(message.MessageResponse.SessionKind), "SessionKind"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.MessageResponse.SessionAction), "SessionAction"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.ListParams.ActiveFilter), "ActiveFilter"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.OrderCompletion.OrderCompletionResult), "OrderCompletionResult"));

    // Generic instantiation — SM types have long @typeName with parens.
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.Write), "Write"));
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.LoginCodeWrite), "LoginCodeWrite"));
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.ExecuteResult), "ExecuteResult"));
}

test "is_ts_identifier validation" {
    comptime assert(is_ts_identifier("Product"));
    comptime assert(is_ts_identifier("foo_bar"));
    comptime assert(is_ts_identifier("_private"));
    comptime assert(is_ts_identifier("A"));
    comptime assert(is_ts_identifier("x123"));

    comptime assert(!is_ts_identifier(""));
    comptime assert(!is_ts_identifier("123abc"));
    comptime assert(!is_ts_identifier("foo-bar"));
    comptime assert(!is_ts_identifier("foo.bar"));
    comptime assert(!is_ts_identifier("foo bar"));
}

test "is_known_struct covers all union variant types" {
    // Every non-void, non-primitive Result variant type is known.
    comptime {
        for (@typeInfo(message.Result).@"union".fields) |field| {
            if (field.type == void) continue;
            if (@typeInfo(field.type) == .int) continue;
            assert(is_known_struct(field.type));
        }
    }

    // Every non-void Write variant is either known or anonymous (struct).
    comptime {
        for (@typeInfo(SM.Write).@"union".fields) |field| {
            if (field.type == void) continue;
            const info = @typeInfo(field.type);
            if (info == .@"struct") continue;
            assert(info == .int or info == .bool or info == .@"enum");
        }
    }
}

test "output is valid structure" {
    comptime assert(std.mem.startsWith(u8, &output, "// Auto-generated"));

    comptime {
        @setEvalBranchQuota(200000);
        var interfaces: usize = 0;
        var types: usize = 0;
        var consts: usize = 0;
        var i: usize = 0;
        while (i + 16 < output.len) : (i += 1) {
            if (std.mem.eql(u8, output[i..][0..16], "export interface")) interfaces += 1;
            if (i + 11 <= output.len and std.mem.eql(u8, output[i..][0..11], "export type")) types += 1;
            if (i + 12 <= output.len and std.mem.eql(u8, output[i..][0..12], "export const")) consts += 1;
        }
        // 14 extern + 2 flags + 8 regular + 3 SM-internal + 3 anon = 30 interfaces
        assert(interfaces == 30);
        // 9 enum type aliases + 2 union type aliases = 11 types
        assert(types == 11);
        // 14 constants + 9 Values consts = 23 consts
        assert(consts == 23);
    }
}
