const std = @import("std");
const assert = std.debug.assert;
const stdx = @import("tiger_framework").stdx;
const message = @import("message.zig");
const state_machine = @import("state_machine.zig");
const protocol = @import("protocol.zig");

const SM = state_machine.StateMachineType(state_machine.MemoryStorage);

/// Single source of truth for all struct types emitted as TS interfaces.
/// The emit block, is_known_struct, and the uniqueness assertion all
/// derive from this list. Adding a type here is the only step needed.
const known_structs = .{
    // Extern structs
    message.Product,
    message.ProductCollection,
    message.InventoryTransfer,
    message.OrderItem,
    message.OrderRequest,
    message.OrderCompletion,
    message.OrderResultItem,
    message.OrderResult,
    message.OrderSummary,
    message.SearchQuery,
    message.ListParams,
    message.LoginCodeRequest,
    message.LoginVerification,
    message.Message,
    // Flags
    message.ProductFlags,
    message.CollectionFlags,
    // Regular structs
    message.ProductList,
    message.CollectionWithProducts,
    message.CollectionList,
    message.OrderSummaryList,
    message.PageLoadDashboardResult,
    message.LoginResult,
    message.FollowupState,
    message.MessageResponse,
    // SM-internal
    SM.LoginCodeWrite,
    SM.LoginCodeKey,
    SM.ExecuteResult,
    // Sidecar types
    message.LoginCodeEntry,
    message.PrefetchIdentity,
    // Protocol (translate round trip — generic serde works)
    protocol.TranslateRequest,
    protocol.TranslateResponse,
    // Protocol (execute_render) — WriteSlot uses raw byte data, not typed fields.
    // PrefetchCache uses presence flags, not _len pattern.
    // ExecuteRenderRequest/Response contain these non-standard types.
    // Serde for these is hand-written in the sidecar, not generated.
    protocol.WriteSlot,
};

/// All enum types emitted as TS string literal unions.
const known_enums = .{
    message.Status,
    message.Operation,
    message.OrderStatus,
    message.OrderCompletion.OrderCompletionResult,
    message.ListParams.ActiveFilter,
    message.EventTag,
    state_machine.StorageResult,
    message.MessageResponse.SessionKind,
    message.MessageResponse.SessionAction,
    // Protocol
    protocol.Tag,
    protocol.Method,
};

/// All union types emitted as TS discriminated unions.
const known_unions = .{
    message.Result,
    SM.Write,
};

const output = blk: {
    @setEvalBranchQuota(100000);
    var buf: [65536]u8 = undefined;
    var w = Writer{ .buf = &buf, .pos = 0 };

    w.raw("// Auto-generated by `zig build codegen` — do not edit.\n\n");

    // --- Constants ---
    w.emit_const("body_max", message.body_max);
    w.emit_const("list_max", message.list_max);
    w.emit_const("dashboard_list_max", message.dashboard_list_max);
    w.emit_const("order_items_max", message.order_items_max);
    w.emit_const("product_name_max", message.product_name_max);
    w.emit_const("product_description_max", message.product_description_max);
    w.emit_const("collection_name_max", message.collection_name_max);
    w.emit_const("search_query_max", message.search_query_max);
    w.emit_const("email_max", message.email_max);
    w.emit_const("code_length", message.code_length);
    w.emit_const("payment_ref_max", message.payment_ref_max);
    w.emit_const("order_timeout_seconds", message.order_timeout_seconds);
    w.emit_const("credential_max", message.Message.credential_max);
    w.emit_const("writes_max", SM.writes_max);
    w.emit_const("path_max", protocol.path_max);
    w.emit_const("json_body_max", protocol.json_body_max);
    w.raw("\n");

    // --- Enums ---
    for (known_enums) |T| w.emit_enum(T);

    // --- Structs (dispatch by layout) ---
    for (known_structs) |T| {
        const layout = @typeInfo(T).@"struct".layout;
        if (layout == .@"packed") {
            w.emit_packed_struct(T);
        } else if (layout == .@"extern") {
            w.emit_extern_struct(T);
        } else {
            w.emit_struct(T);
        }
    }

    // --- Anonymous struct interfaces for union variants ---
    for (known_unions) |U| w.emit_union_anon_structs(U);

    // --- Tagged unions ---
    for (known_unions) |U| w.emit_union(U);

    // --- Serde: binary ↔ TypeScript serialization ---
    w.emit_serde_helpers();

    for (known_structs) |T| {
        const layout = @typeInfo(T).@"struct".layout;
        if (layout == .@"packed") {
            w.emit_packed_serde(T);
        } else if (layout == .@"extern") {
            w.emit_extern_serde(T);
        }
    }

    // --- Exhaustiveness assertions ---

    // Union variant counts — if a variant is added, codegen must be updated.
    assert(@typeInfo(message.Result).@"union".fields.len == 10);
    assert(@typeInfo(SM.Write).@"union".fields.len == 11);

    // Anon struct counts — ties emit_union_anon_structs to emit_union.
    assert(count_anon_structs(SM.Write) == 3);
    assert(count_anon_structs(message.Result) == 0);

    // Every Operation.EventType references a type we handle.
    for (@typeInfo(message.Operation).@"enum".fields) |op_field| {
        const op: message.Operation = @enumFromInt(op_field.value);
        const ET = op.EventType();
        if (ET != void) {
            assert(is_known_struct(ET) or @typeInfo(ET) == .int);
        }
    }

    // No two emitted types produce the same TS name.
    assert_no_name_collisions();

    // Buffer headroom — assert we used less than 75% to catch bloat early.
    assert(w.pos > 0);
    assert(w.pos < buf.len * 3 / 4);

    const final = buf[0..w.pos];
    break :blk final[0..final.len].*;
};

pub fn main() !void {
    try std.io.getStdOut().writer().writeAll(&output);
}

// ---------------------------------------------------------------------------
// Writer — comptime string builder
// ---------------------------------------------------------------------------

const Writer = struct {
    buf: *[65536]u8,
    pos: usize,

    fn raw(w: *Writer, s: []const u8) void {
        assert(w.pos + s.len <= w.buf.len);
        @memcpy(w.buf[w.pos..][0..s.len], s);
        w.pos += s.len;
    }

    fn write_pascal(w: *Writer, comptime name: []const u8) void {
        assert(name.len > 0);
        var cap = true;
        for (name) |ch| {
            if (ch == '_') {
                cap = true;
            } else {
                assert(w.pos < w.buf.len);
                w.buf[w.pos] = if (cap and ch >= 'a' and ch <= 'z') ch - 32 else ch;
                w.pos += 1;
                cap = false;
            }
        }
    }

    fn int(w: *Writer, comptime n: comptime_int) void {
        w.raw(int_str(n));
    }

    // --- Constants ---

    fn emit_const(w: *Writer, comptime name: []const u8, comptime value: comptime_int) void {
        w.raw("export const ");
        w.raw(name);
        w.raw(" = ");
        w.int(value);
        w.raw(";\n");
    }

    // --- Enums ---
    // Name derived from type — no free string parameter.

    fn emit_enum(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const info = @typeInfo(T).@"enum";
        const fields = info.fields;
        assert(fields.len > 0);
        // Serde uses dv.getUint8/setUint8 — enum must fit in one byte.
        assert(@sizeOf(T) == 1);

        w.raw("export type ");
        w.raw(name);
        w.raw(" =\n");
        for (fields) |field| {
            assert(is_ts_identifier(field.name));
            w.raw("  | \"");
            w.raw(field.name);
            w.raw("\"\n");
        }
        w.raw("  ;\n\n");

        w.raw("export const ");
        w.raw(name);
        w.raw("Values = {\n");
        for (fields) |field| {
            w.raw("  ");
            w.raw(field.name);
            w.raw(": ");
            w.int(field.value);
            w.raw(",\n");
        }
        w.raw("} as const;\n\n");
    }

    // --- Packed flag structs ---

    fn emit_packed_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        assert(@typeInfo(T).@"struct".layout == .@"packed");

        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");
        var bool_count: usize = 0;
        for (@typeInfo(T).@"struct".fields) |field| {
            if (std.mem.eql(u8, field.name, "padding")) continue;
            if (field.type != bool) continue;
            bool_count += 1;
            w.raw("  ");
            w.raw(field.name);
            w.raw(": boolean;\n");
        }
        assert(bool_count > 0);
        w.raw("}\n\n");
    }

    // --- Extern structs (with @offset/@size JSDoc) ---

    fn emit_extern_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const info = @typeInfo(T).@"struct";
        assert(info.layout == .@"extern");
        assert(stdx.no_padding(T));

        w.raw("/** @size ");
        w.int(@sizeOf(T));
        w.raw(" */\n");
        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");

        var field_count: usize = 0;
        for (info.fields) |field| {
            if (should_skip(T, field.name)) continue;
            field_count += 1;

            // JSDoc with offset (and @max for arrays with _len companion)
            w.raw("  /** @offset ");
            w.int(@offsetOf(T, field.name));
            if (is_array_type(field.type) and has_len_companion(T, field.name)) {
                w.raw(" @max ");
                w.int(@typeInfo(field.type).array.len);
            }
            w.raw(" */\n");

            w.emit_field_decl(T, field);
        }
        assert(field_count > 0);

        w.raw("}\n\n");
    }

    // --- Regular structs (no offset JSDoc) ---
    // Asserts the type is NOT extern or packed — those have dedicated emit
    // functions. Calling this on an extern struct would silently drop @offset
    // JSDoc that the serde layer depends on.

    fn emit_struct(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const layout = @typeInfo(T).@"struct".layout;
        assert(layout != .@"extern");
        assert(layout != .@"packed");

        w.raw("export interface ");
        w.raw(name);
        w.raw(" {\n");

        for (@typeInfo(T).@"struct".fields) |field| {
            if (should_skip(T, field.name)) continue;

            if (is_array_type(field.type) and has_len_companion(T, field.name)) {
                w.raw("  /** @max ");
                w.int(@typeInfo(field.type).array.len);
                w.raw(" */\n");
            }

            w.emit_field_decl(T, field);
        }

        w.raw("}\n\n");
    }

    // --- Shared field declaration ---

    fn emit_field_decl(w: *Writer, comptime StructT: type, comptime field: std.builtin.Type.StructField) void {
        w.raw("  ");
        w.raw(field.name);
        w.raw(": ");
        w.write_field_type(StructT, field);
        w.raw(";\n");
    }

    fn write_field_type(w: *Writer, comptime StructT: type, comptime field: std.builtin.Type.StructField) void {
        if (is_array_type(field.type)) {
            const arr = @typeInfo(field.type).array;
            if (arr.child != u8) {
                // [N]T where T != u8 → T[] regardless of _len companion.
                w.write_ts_type(arr.child);
                w.raw("[]");
            } else if (has_len_companion(StructT, field.name)) {
                // [N]u8 with _len → string.
                w.raw("string");
            } else {
                // [N]u8 without _len → Uint8Array.
                w.raw("Uint8Array");
            }
            return;
        }
        w.write_ts_type(field.type);
    }

    fn write_ts_type(w: *Writer, comptime T: type) void {
        switch (@typeInfo(T)) {
            .int => |i| {
                if (i.bits == 128) w.raw("string") else w.raw("number");
            },
            .bool => w.raw("boolean"),
            .void => w.raw("void"),
            .@"enum" => w.raw(type_leaf_name(T)),
            .@"struct" => w.raw(type_leaf_name(T)),
            .@"union" => w.raw(type_leaf_name(T)),
            .optional => |opt| {
                w.write_ts_type(opt.child);
                w.raw(" | null");
            },
            else => @compileError("unhandled type: " ++ @typeName(T)),
        }
    }

    // --- Anonymous struct interfaces for union variants ---

    fn emit_union_anon_structs(w: *Writer, comptime U: type) void {
        const prefix = type_leaf_name(U);
        for (@typeInfo(U).@"union".fields) |field| {
            if (field.type == void) continue;
            if (@typeInfo(field.type) != .@"struct") continue;
            if (is_known_struct(field.type)) continue;

            w.raw("export interface ");
            w.raw(prefix);
            w.write_pascal(field.name);
            w.raw(" {\n");

            for (@typeInfo(field.type).@"struct".fields) |sf| {
                if (should_skip(field.type, sf.name)) continue;

                if (is_array_type(sf.type) and has_len_companion(field.type, sf.name)) {
                    w.raw("  /** @max ");
                    w.int(@typeInfo(sf.type).array.len);
                    w.raw(" */\n");
                }

                w.emit_field_decl(field.type, sf);
            }

            w.raw("}\n\n");
        }
    }

    // --- Tagged unions ---

    fn emit_union(w: *Writer, comptime U: type) void {
        const name = type_leaf_name(U);
        w.raw("export type ");
        w.raw(name);
        w.raw(" =\n");

        for (@typeInfo(U).@"union".fields) |field| {
            w.raw("  | { tag: \"");
            w.raw(field.name);
            w.raw("\"");
            if (field.type != void) {
                w.raw("; value: ");
                w.write_variant_type(U, field.name, field.type);
            }
            w.raw(" }\n");
        }

        w.raw("  ;\n\n");
    }

    /// Variant type reference — delegates to write_ts_type for all known types.
    /// Only overrides the struct branch for anonymous structs, which get a
    /// generated name (union prefix + PascalCase variant name).
    fn write_variant_type(w: *Writer, comptime U: type, comptime variant_name: []const u8, comptime T: type) void {
        if (@typeInfo(T) == .@"struct" and !is_known_struct(T)) {
            w.raw(type_leaf_name(U));
            w.write_pascal(variant_name);
        } else {
            w.write_ts_type(T);
        }
    }

    // =======================================================================
    // Serde — binary ↔ TypeScript serialization
    // =======================================================================

    fn emit_serde_helpers(w: *Writer) void {
        w.raw("// --- Serde ---\n\n");
        w.raw("const _decoder = new TextDecoder();\n");
        w.raw("const _encoder = new TextEncoder();\n\n");

        // readU128 / writeU128
        w.raw("function readU128(dv: DataView, offset: number): string {\n");
        w.raw("  const lo = dv.getBigUint64(offset, true);\n");
        w.raw("  const hi = dv.getBigUint64(offset + 8, true);\n");
        w.raw("  return ((hi << 64n) | lo).toString(16).padStart(32, '0');\n");
        w.raw("}\n\n");

        w.raw("function writeU128(dv: DataView, offset: number, hex: string): void {\n");
        w.raw("  const val = BigInt('0x' + (hex || '0'));\n");
        w.raw("  dv.setBigUint64(offset, val & 0xFFFFFFFFFFFFFFFFn, true);\n");
        w.raw("  dv.setBigUint64(offset + 8, val >> 64n, true);\n");
        w.raw("}\n\n");

        // readEnum / writeEnum
        w.raw("function readEnum<T extends string>(dv: DataView, offset: number, values: Record<string, number>): T {\n");
        w.raw("  const byte = dv.getUint8(offset);\n");
        w.raw("  for (const [name, val] of Object.entries(values)) {\n");
        w.raw("    if (val === byte) return name as T;\n");
        w.raw("  }\n");
        w.raw("  throw new Error('invalid enum value: ' + byte);\n");
        w.raw("}\n\n");

        w.raw("function writeEnum(dv: DataView, offset: number, values: Record<string, number>, name: string): void {\n");
        w.raw("  dv.setUint8(offset, values[name]);\n");
        w.raw("}\n\n");
    }

    fn emit_packed_serde(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const info = @typeInfo(T).@"struct";
        assert(info.layout == .@"packed");
        assert(@sizeOf(T) == 1); // Packed flags must fit in a single byte.
        const fields = info.fields;

        // Read function
        w.raw("function read");
        w.raw(name);
        w.raw("(dv: DataView, offset: number): ");
        w.raw(name);
        w.raw(" {\n  const byte = dv.getUint8(offset);\n  return {\n");
        for (fields) |field| {
            if (std.mem.eql(u8, field.name, "padding")) continue;
            if (field.type != bool) continue;
            w.raw("    ");
            w.raw(field.name);
            w.raw(": (byte & ");
            w.int(@as(u8, 1) << @bitOffsetOf(T, field.name));
            w.raw(") !== 0,\n");
        }
        w.raw("  };\n}\n\n");

        // Write function
        w.raw("function write");
        w.raw(name);
        w.raw("(dv: DataView, offset: number, val: ");
        w.raw(name);
        w.raw("): void {\n  dv.setUint8(offset, ");
        var first = true;
        for (fields) |field| {
            if (std.mem.eql(u8, field.name, "padding")) continue;
            if (field.type != bool) continue;
            if (!first) w.raw(" | ");
            first = false;
            w.raw("(val.");
            w.raw(field.name);
            w.raw(" ? ");
            w.int(@as(u8, 1) << @bitOffsetOf(T, field.name));
            w.raw(" : 0)");
        }
        w.raw(");\n}\n\n");
    }

    fn emit_extern_serde(w: *Writer, comptime T: type) void {
        const name = type_leaf_name(T);
        const info = @typeInfo(T).@"struct";
        assert(info.layout == .@"extern");
        assert(stdx.no_padding(T));
        const fields = info.fields;

        // --- Read function ---
        w.raw("export function read");
        w.raw(name);
        w.raw("(data: Uint8Array, offset: number): ");
        w.raw(name);
        w.raw(" {\n");
        w.raw("  const dv = new DataView(data.buffer, data.byteOffset, data.byteLength);\n");
        w.raw("  return {\n");
        for (fields) |field| {
            if (should_skip(T, field.name)) continue;
            w.emit_serde_read_field(T, field);
        }
        w.raw("  };\n}\n\n");

        // --- Write function ---
        // Each byte written exactly once. Reserved/padding regions zeroed.
        // _len companions written by their parent field — not zeroed here.
        // String/array buffers zeroed by emit_serde_write_field before encode.
        w.raw("export function write");
        w.raw(name);
        w.raw("(data: Uint8Array, offset: number, val: ");
        w.raw(name);
        w.raw("): void {\n");
        w.raw("  const dv = new DataView(data.buffer, data.byteOffset, data.byteLength);\n");
        for (fields) |field| {
            if (should_skip(T, field.name)) {
                // Only zero reserved/padding — _len fields are set by their
                // parent's write, so emitting a zero here would be a redundant write.
                if (is_reserved_or_padding(field.name)) {
                    w.raw("  data.fill(0, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", offset + ");
                    w.int(@offsetOf(T, field.name) + @sizeOf(field.type));
                    w.raw(");\n");
                }
                continue;
            }
            w.emit_serde_write_field(T, field);
        }
        w.raw("}\n\n");
    }

    // --- Serde field read (expression inside object literal) ---

    fn emit_serde_read_field(w: *Writer, comptime T: type, comptime field: std.builtin.Type.StructField) void {
        w.raw("    ");
        w.raw(field.name);
        w.raw(": ");

        if (is_array_type(field.type)) {
            const arr = @typeInfo(field.type).array;
            if (arr.child != u8) {
                // [N]T array → Array.from(...)
                const li = get_len_info(T, field.name);
                w.raw("Array.from({ length: ");
                w.emit_dv_read(li);
                w.raw(" }, (_, i) =>\n      read");
                w.raw(type_leaf_name(arr.child));
                w.raw("(data, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(" + i * ");
                w.int(@sizeOf(arr.child));
                w.raw("))");
            } else if (has_len_companion(T, field.name)) {
                // [N]u8 with _len → string
                const li = get_len_info(T, field.name);
                w.raw("_decoder.decode(data.subarray(offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(" + ");
                w.emit_dv_read(li);
                w.raw("))");
            } else {
                // [N]u8 without _len → Uint8Array copy
                w.raw("data.slice(offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", offset + ");
                w.int(@offsetOf(T, field.name) + arr.len);
                w.raw(")");
            }
        } else {
            w.emit_scalar_read(T, field);
        }

        w.raw(",\n");
    }

    fn emit_scalar_read(w: *Writer, comptime T: type, comptime field: std.builtin.Type.StructField) void {
        const ft = @typeInfo(field.type);
        switch (ft) {
            .int => |i| {
                if (i.bits == 128) {
                    w.raw("readU128(dv, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(")");
                } else if (i.bits == 64) {
                    w.raw("Number(dv.getBig");
                    if (i.signedness == .signed) w.raw("Int64(offset + ") else w.raw("Uint64(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", true))");
                } else if (i.bits == 32) {
                    w.raw("dv.getUint32(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", true)");
                } else if (i.bits == 16) {
                    w.raw("dv.getUint16(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", true)");
                } else {
                    w.raw("dv.getUint8(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(")");
                }
            },
            .@"enum" => {
                w.raw("readEnum<");
                w.raw(type_leaf_name(field.type));
                w.raw(">(dv, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", ");
                w.raw(type_leaf_name(field.type));
                w.raw("Values)");
            },
            .@"struct" => |s| {
                if (s.layout == .@"packed") {
                    w.raw("read");
                    w.raw(type_leaf_name(field.type));
                    w.raw("(dv, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(")");
                } else {
                    assert(s.layout == .@"extern");
                    w.raw("read");
                    w.raw(type_leaf_name(field.type));
                    w.raw("(data, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(")");
                }
            },
            .bool => {
                w.raw("dv.getUint8(offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(") !== 0");
            },
            else => @compileError("unhandled serde read type: " ++ @typeName(field.type)),
        }
    }

    // --- Serde field write (statements) ---

    fn emit_serde_write_field(w: *Writer, comptime T: type, comptime field: std.builtin.Type.StructField) void {
        if (is_array_type(field.type)) {
            const arr = @typeInfo(field.type).array;
            if (arr.child != u8) {
                // [N]T array — validate, loop, write length
                const li = get_len_info(T, field.name);
                const len_max = (@as(u64, 1) << li.bits) - 1;
                const arr_max = @min(arr.len, len_max);
                // Zero the full array region, then write populated items.
                w.raw("  data.fill(0, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", offset + ");
                w.int(@offsetOf(T, field.name) + arr.len * @sizeOf(arr.child));
                w.raw(");\n");
                w.raw("  if (val.");
                w.raw(field.name);
                w.raw(".length > ");
                w.int(arr_max);
                w.raw(") throw new Error('");
                w.raw(field.name);
                w.raw(" too long: ' + val.");
                w.raw(field.name);
                w.raw(".length);\n");
                w.raw("  for (let i = 0; i < val.");
                w.raw(field.name);
                w.raw(".length; i++) write");
                w.raw(type_leaf_name(arr.child));
                w.raw("(data, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(" + i * ");
                w.int(@sizeOf(arr.child));
                w.raw(", val.");
                w.raw(field.name);
                w.raw("[i]);\n");
                // Write length
                w.raw("  ");
                w.emit_dv_write_start(li);
                w.raw("val.");
                w.raw(field.name);
                w.raw(".length");
                w.emit_dv_write_end(li);
                w.raw(";\n");
            } else if (has_len_companion(T, field.name)) {
                // [N]u8 with _len → string, with length validation
                const li = get_len_info(T, field.name);
                const len_max = (@as(u64, 1) << li.bits) - 1;
                // Zero the full buffer, encode string, validate + write length.
                w.raw("  data.fill(0, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", offset + ");
                w.int(@offsetOf(T, field.name) + arr.len);
                w.raw(");\n");
                w.raw("  { const _n = _encoder.encodeInto(val.");
                w.raw(field.name);
                w.raw(", data.subarray(offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", offset + ");
                w.int(@offsetOf(T, field.name) + arr.len);
                w.raw(")).written; ");
                w.raw("if (_n > ");
                w.int(len_max);
                w.raw(") throw new Error('");
                w.raw(field.name);
                w.raw(" too long: ' + _n); ");
                w.emit_dv_write_start(li);
                w.raw("_n");
                w.emit_dv_write_end(li);
                w.raw("; }\n");
            } else {
                // [N]u8 without _len → Uint8Array
                w.raw("  data.set(val.");
                w.raw(field.name);
                w.raw(".subarray(0, ");
                w.int(arr.len);
                w.raw("), offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(");\n");
            }
        } else {
            w.emit_scalar_write(T, field);
        }
    }

    fn emit_scalar_write(w: *Writer, comptime T: type, comptime field: std.builtin.Type.StructField) void {
        const ft = @typeInfo(field.type);
        switch (ft) {
            .int => |i| {
                if (i.bits == 128) {
                    w.raw("  writeU128(dv, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(");\n");
                } else if (i.bits == 64) {
                    w.raw("  dv.setBig");
                    if (i.signedness == .signed) w.raw("Int64(offset + ") else w.raw("Uint64(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", BigInt(val.");
                    w.raw(field.name);
                    w.raw("), true);\n");
                } else if (i.bits == 32) {
                    w.raw("  dv.setUint32(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(", true);\n");
                } else if (i.bits == 16) {
                    w.raw("  dv.setUint16(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(", true);\n");
                } else {
                    w.raw("  dv.setUint8(offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(");\n");
                }
            },
            .@"enum" => {
                w.raw("  writeEnum(dv, offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", ");
                w.raw(type_leaf_name(field.type));
                w.raw("Values, val.");
                w.raw(field.name);
                w.raw(");\n");
            },
            .@"struct" => |s| {
                if (s.layout == .@"packed") {
                    w.raw("  write");
                    w.raw(type_leaf_name(field.type));
                    w.raw("(dv, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(");\n");
                } else {
                    assert(s.layout == .@"extern");
                    w.raw("  write");
                    w.raw(type_leaf_name(field.type));
                    w.raw("(data, offset + ");
                    w.int(@offsetOf(T, field.name));
                    w.raw(", val.");
                    w.raw(field.name);
                    w.raw(");\n");
                }
            },
            .bool => {
                w.raw("  dv.setUint8(offset + ");
                w.int(@offsetOf(T, field.name));
                w.raw(", val.");
                w.raw(field.name);
                w.raw(" ? 1 : 0);\n");
            },
            else => @compileError("unhandled serde write type: " ++ @typeName(field.type)),
        }
    }

    // --- DataView read/write for _len companion fields ---

    fn emit_dv_read(w: *Writer, comptime li: LenInfo) void {
        switch (li.bits) {
            8 => {
                w.raw("dv.getUint8(offset + ");
                w.int(li.offset);
                w.raw(")");
            },
            16 => {
                w.raw("dv.getUint16(offset + ");
                w.int(li.offset);
                w.raw(", true)");
            },
            32 => {
                w.raw("dv.getUint32(offset + ");
                w.int(li.offset);
                w.raw(", true)");
            },
            else => unreachable,
        }
    }

    fn emit_dv_write_start(w: *Writer, comptime li: LenInfo) void {
        switch (li.bits) {
            8 => {
                w.raw("dv.setUint8(offset + ");
                w.int(li.offset);
                w.raw(", ");
            },
            16 => {
                w.raw("dv.setUint16(offset + ");
                w.int(li.offset);
                w.raw(", ");
            },
            32 => {
                w.raw("dv.setUint32(offset + ");
                w.int(li.offset);
                w.raw(", ");
            },
            else => unreachable,
        }
    }

    fn emit_dv_write_end(w: *Writer, comptime li: LenInfo) void {
        switch (li.bits) {
            8 => w.raw(")"),
            16, 32 => w.raw(", true)"),
            else => unreachable,
        }
    }
};

// ---------------------------------------------------------------------------
// Comptime helpers
// ---------------------------------------------------------------------------

fn int_str(comptime n: comptime_int) []const u8 {
    if (n == 0) return "0";
    var buf_local: [20]u8 = undefined;
    var pos: usize = 20;
    var val = if (n < 0) -n else n;
    while (val > 0) {
        pos -= 1;
        buf_local[pos] = @intCast('0' + val % 10);
        val = val / 10;
    }
    if (n < 0) {
        pos -= 1;
        buf_local[pos] = '-';
    }
    return buf_local[pos..20];
}

fn type_leaf_name(comptime T: type) []const u8 {
    const full = @typeName(T);
    var last_dot: usize = 0;
    for (full, 0..) |ch, i| {
        if (ch == '.') last_dot = i + 1;
    }
    const name = if (last_dot == 0) full else full[last_dot..];
    assert(name.len > 0);
    assert(is_ts_identifier(name));
    return name;
}

/// Returns true if s is a valid TypeScript identifier (ASCII letters, digits, underscores).
fn is_ts_identifier(comptime s: []const u8) bool {
    if (s.len == 0) return false;
    if (!((s[0] >= 'a' and s[0] <= 'z') or (s[0] >= 'A' and s[0] <= 'Z') or s[0] == '_')) return false;
    for (s[1..]) |ch| {
        if (!((ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z') or (ch >= '0' and ch <= '9') or ch == '_')) return false;
    }
    return true;
}

fn is_array_type(comptime T: type) bool {
    return @typeInfo(T) == .array;
}

fn has_field(comptime StructT: type, comptime name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, name)) return true;
    }
    return false;
}

/// Checks whether `field_name` has a length companion field in StructT.
/// Detects `{name}_len` and the `items` + `len` pattern.
/// Asserts the base field is actually an array — if not, the _len naming
/// convention is misleading and the codegen would produce wrong output.
fn has_len_companion(comptime StructT: type, comptime field_name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (f.name.len == field_name.len + 4 and
            std.mem.eql(u8, f.name[0..field_name.len], field_name) and
            std.mem.eql(u8, f.name[field_name.len..], "_len"))
        {
            assert(is_array_field(StructT, field_name));
            return true;
        }
    }
    if (std.mem.eql(u8, field_name, "items") and has_field(StructT, "len")) {
        assert(is_array_field(StructT, "items"));
        return true;
    }
    return false;
}

/// Offset and bit-width of a _len companion field, used by serde emitters
/// to generate the correct DataView read/write call.
const LenInfo = struct {
    offset: usize,
    bits: u16,
};

/// Returns the offset and type of the _len companion for a given field.
/// Caller must have verified has_len_companion() returns true.
/// Asserts the companion field is an unsigned integer (u8, u16, or u32).
fn get_len_info(comptime StructT: type, comptime field_name: []const u8) LenInfo {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (f.name.len == field_name.len + 4 and
            std.mem.eql(u8, f.name[0..field_name.len], field_name) and
            std.mem.eql(u8, f.name[field_name.len..], "_len"))
        {
            assert(@typeInfo(f.type) == .int);
            assert(@typeInfo(f.type).int.signedness == .unsigned);
            return .{ .offset = @offsetOf(StructT, f.name), .bits = @typeInfo(f.type).int.bits };
        }
    }
    // items + len pattern
    if (std.mem.eql(u8, field_name, "items")) {
        for (@typeInfo(StructT).@"struct".fields) |f| {
            if (std.mem.eql(u8, f.name, "len")) {
                assert(@typeInfo(f.type) == .int);
                assert(@typeInfo(f.type).int.signedness == .unsigned);
                return .{ .offset = @offsetOf(StructT, f.name), .bits = @typeInfo(f.type).int.bits };
            }
        }
    }
    unreachable;
}

/// Returns true if the named field in StructT is an array type.
fn is_array_field(comptime StructT: type, comptime field_name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, field_name)) return is_array_type(f.type);
    }
    return false;
}

/// Returns true if the field name is a reserved or padding region (not a _len companion).
fn is_reserved_or_padding(comptime field_name: []const u8) bool {
    return std.mem.startsWith(u8, field_name, "reserved") or std.mem.eql(u8, field_name, "padding");
}

/// Returns true if a field should be omitted from the TS output.
fn should_skip(comptime StructT: type, comptime field_name: []const u8) bool {
    if (std.mem.startsWith(u8, field_name, "reserved")) return true;
    if (std.mem.eql(u8, field_name, "padding")) return true;

    // Skip _len companions (e.g., "name_len" when "name" exists)
    if (field_name.len > 4 and std.mem.eql(u8, field_name[field_name.len - 4 ..], "_len")) {
        const base = field_name[0 .. field_name.len - 4];
        if (has_field(StructT, base)) return true;
    }

    // Skip bare "len" when there's an "items" field (list structs)
    if (std.mem.eql(u8, field_name, "len") and has_field(StructT, "items")) return true;

    return false;
}

/// Counts union variants whose type is an anonymous struct (not in is_known_struct).
fn count_anon_structs(comptime U: type) usize {
    var count: usize = 0;
    for (@typeInfo(U).@"union".fields) |field| {
        if (field.type == void) continue;
        if (@typeInfo(field.type) != .@"struct") continue;
        if (!is_known_struct(field.type)) count += 1;
    }
    return count;
}

/// Returns true if T is a struct in the known_structs list.
fn is_known_struct(comptime T: type) bool {
    comptime assert(known_structs.len == 32);
    comptime {
        for (known_structs) |K| assert(@typeInfo(K) == .@"struct");
    }
    inline for (known_structs) |K| {
        if (T == K) return true;
    }
    return false;
}

/// Returns true if T is an enum in the known_enums list.
fn is_known_enum(comptime T: type) bool {
    comptime assert(known_enums.len == 11);
    comptime {
        for (known_enums) |E| assert(@typeInfo(E) == .@"enum");
    }
    inline for (known_enums) |E| {
        if (T == E) return true;
    }
    return false;
}

/// Returns true if T is a union in the known_unions list.
fn is_known_union(comptime T: type) bool {
    comptime assert(known_unions.len == 2);
    comptime {
        for (known_unions) |U| assert(@typeInfo(U) == .@"union");
    }
    inline for (known_unions) |U| {
        if (T == U) return true;
    }
    return false;
}

/// Asserts no two emitted types produce the same TS name.
/// Checks across all categories: enums, structs, unions, anonymous interfaces.
fn assert_no_name_collisions() void {
    @setEvalBranchQuota(200000);
    // Struct leaf names are unique among themselves.
    inline for (known_structs) |K1| {
        var count: usize = 0;
        inline for (known_structs) |K2| {
            if (std.mem.eql(u8, type_leaf_name(K1), type_leaf_name(K2))) count += 1;
        }
        assert(count == 1);
    }

    // Enum leaf names are unique among themselves.
    inline for (known_enums) |E1| {
        var count: usize = 0;
        inline for (known_enums) |E2| {
            if (std.mem.eql(u8, type_leaf_name(E1), type_leaf_name(E2))) count += 1;
        }
        assert(count == 1);
    }

    // No enum name collides with a struct name.
    inline for (known_enums) |E| {
        inline for (known_structs) |S| {
            assert(!std.mem.eql(u8, type_leaf_name(E), type_leaf_name(S)));
        }
    }

    // No union name collides with an enum or struct name.
    inline for (known_unions) |U| {
        inline for (known_enums) |E| {
            assert(!std.mem.eql(u8, type_leaf_name(U), type_leaf_name(E)));
        }
        inline for (known_structs) |S| {
            assert(!std.mem.eql(u8, type_leaf_name(U), type_leaf_name(S)));
        }
    }

    // Every enum/union/struct type referenced as a field is in the known lists.
    // If someone adds a new type to message.zig and uses it in a struct field
    // without adding it to the appropriate known list, this assertion catches it.
    inline for (known_structs) |S| {
        inline for (@typeInfo(S).@"struct".fields) |field| {
            if (@typeInfo(field.type) == .@"enum") {
                assert(is_known_enum(field.type));
            }
            if (@typeInfo(field.type) == .@"union") {
                assert(is_known_union(field.type));
            }
            // Nested struct fields (e.g., CollectionWithProducts.products: ProductList)
            // must be in known_structs so the serde generates readX/writeX for them.
            if (@typeInfo(field.type) == .@"struct") {
                assert(is_known_struct(field.type));
            }
            // Check optional children (e.g., ?FollowupState).
            if (@typeInfo(field.type) == .optional) {
                const child = @typeInfo(field.type).optional.child;
                if (@typeInfo(child) == .@"enum") assert(is_known_enum(child));
                if (@typeInfo(child) == .@"union") assert(is_known_union(child));
                if (@typeInfo(child) == .@"struct") assert(is_known_struct(child));
            }
        }
    }
}

// =====================================================================
// Tests
// =====================================================================

test "int_str decimal formatting" {
    comptime assert(std.mem.eql(u8, int_str(0), "0"));
    comptime assert(std.mem.eql(u8, int_str(7), "7"));
    comptime assert(std.mem.eql(u8, int_str(42), "42"));
    comptime assert(std.mem.eql(u8, int_str(672), "672"));
    comptime assert(std.mem.eql(u8, int_str(-1), "-1"));
    comptime assert(std.mem.eql(u8, int_str(-60), "-60"));
    comptime assert(std.mem.eql(u8, int_str(message.body_max), "672"));
    comptime assert(std.mem.eql(u8, int_str(message.list_max), "50"));
    comptime assert(std.mem.eql(u8, int_str(SM.writes_max), "21"));
    comptime assert(std.mem.eql(u8, int_str(@sizeOf(message.Message)), "880"));
}

test "should_skip field filtering" {
    // Reserved fields — always skipped.
    comptime assert(should_skip(message.ProductCollection, "reserved"));
    comptime assert(should_skip(message.InventoryTransfer, "reserved"));
    comptime assert(should_skip(message.Message, "reserved"));

    // Padding — always skipped.
    comptime assert(should_skip(message.ProductFlags, "padding"));

    // _len companions — skipped when base field exists.
    comptime assert(should_skip(message.Product, "name_len"));
    comptime assert(should_skip(message.Product, "description_len"));
    comptime assert(should_skip(message.OrderResult, "items_len"));
    comptime assert(should_skip(message.OrderResult, "payment_ref_len"));
    comptime assert(should_skip(message.Message, "credential_len"));

    // Bare "len" — skipped when "items" exists.
    comptime assert(should_skip(message.ProductList, "len"));
    comptime assert(should_skip(message.CollectionList, "len"));
    comptime assert(should_skip(message.OrderSummaryList, "len"));

    // items_len on OrderSummary — NOT a companion (no "items" array field).
    comptime assert(!should_skip(message.OrderSummary, "items_len"));

    // Regular fields — never skipped.
    comptime assert(!should_skip(message.Product, "id"));
    comptime assert(!should_skip(message.Product, "name"));
    comptime assert(!should_skip(message.Product, "price_cents"));
    comptime assert(!should_skip(message.Product, "flags"));
    comptime assert(!should_skip(message.OrderResult, "status"));
    comptime assert(!should_skip(message.Message, "operation"));
    comptime assert(!should_skip(message.Message, "body"));
}

test "has_len_companion detection" {
    // Byte arrays with _len.
    comptime assert(has_len_companion(message.Product, "name"));
    comptime assert(has_len_companion(message.Product, "description"));
    comptime assert(has_len_companion(message.OrderCompletion, "payment_ref"));
    comptime assert(has_len_companion(message.Message, "credential"));
    comptime assert(has_len_companion(message.LoginCodeRequest, "email"));

    // Typed arrays with _len.
    comptime assert(has_len_companion(message.OrderRequest, "items"));
    comptime assert(has_len_companion(message.OrderResult, "items"));

    // items + len pattern (list structs).
    comptime assert(has_len_companion(message.ProductList, "items"));
    comptime assert(has_len_companion(message.CollectionList, "items"));

    // Fields without companions.
    comptime assert(!has_len_companion(message.Product, "id"));
    comptime assert(!has_len_companion(message.Product, "price_cents"));
    comptime assert(!has_len_companion(message.Product, "flags"));
    comptime assert(!has_len_companion(message.Message, "body"));
    comptime assert(!has_len_companion(message.LoginVerification, "code"));
}

test "type_leaf_name extracts last segment" {
    // Simple module-qualified names.
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Product), "Product"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Status), "Status"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.Operation), "Operation"));

    // Nested types (enum inside struct).
    comptime assert(std.mem.eql(u8, type_leaf_name(message.MessageResponse.SessionKind), "SessionKind"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.MessageResponse.SessionAction), "SessionAction"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.ListParams.ActiveFilter), "ActiveFilter"));
    comptime assert(std.mem.eql(u8, type_leaf_name(message.OrderCompletion.OrderCompletionResult), "OrderCompletionResult"));

    // Generic instantiation — SM types have long @typeName with parens.
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.Write), "Write"));
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.LoginCodeWrite), "LoginCodeWrite"));
    comptime assert(std.mem.eql(u8, type_leaf_name(SM.ExecuteResult), "ExecuteResult"));
}

test "get_len_info offset and bit width" {
    // u8 _len companions.
    comptime {
        const name_li = get_len_info(message.Product, "name");
        assert(name_li.offset == @offsetOf(message.Product, "name_len"));
        assert(name_li.bits == 8);
    }

    // u16 _len companions.
    comptime {
        const desc_li = get_len_info(message.Product, "description");
        assert(desc_li.offset == @offsetOf(message.Product, "description_len"));
        assert(desc_li.bits == 16);
    }

    // u32 _len via items + len pattern.
    comptime {
        const items_li = get_len_info(message.ProductList, "items");
        assert(items_li.bits == 32);
    }

    // Typed array _len (OrderRequest.items + items_len).
    comptime {
        const items_li = get_len_info(message.OrderRequest, "items");
        assert(items_li.offset == @offsetOf(message.OrderRequest, "items_len"));
        assert(items_li.bits == 8);
    }

    // Credential _len on Message.
    comptime {
        const cred_li = get_len_info(message.Message, "credential");
        assert(cred_li.offset == @offsetOf(message.Message, "credential_len"));
        assert(cred_li.bits == 8);
    }
}

test "is_ts_identifier validation" {
    comptime assert(is_ts_identifier("Product"));
    comptime assert(is_ts_identifier("foo_bar"));
    comptime assert(is_ts_identifier("_private"));
    comptime assert(is_ts_identifier("A"));
    comptime assert(is_ts_identifier("x123"));

    comptime assert(!is_ts_identifier(""));
    comptime assert(!is_ts_identifier("123abc"));
    comptime assert(!is_ts_identifier("foo-bar"));
    comptime assert(!is_ts_identifier("foo.bar"));
    comptime assert(!is_ts_identifier("foo bar"));
}

test "is_known_struct covers all union variant types" {
    // Every non-void, non-primitive Result variant type is known.
    comptime {
        for (@typeInfo(message.Result).@"union".fields) |field| {
            if (field.type == void) continue;
            if (@typeInfo(field.type) == .int) continue;
            assert(is_known_struct(field.type));
        }
    }

    // Every non-void Write variant is either known or anonymous (struct).
    comptime {
        for (@typeInfo(SM.Write).@"union".fields) |field| {
            if (field.type == void) continue;
            const info = @typeInfo(field.type);
            if (info == .@"struct") continue;
            assert(info == .int or info == .bool or info == .@"enum");
        }
    }
}

test "output is valid structure" {
    comptime assert(std.mem.startsWith(u8, &output, "// Auto-generated"));

    comptime {
        @setEvalBranchQuota(200000);
        var interfaces: usize = 0;
        var types: usize = 0;
        var consts: usize = 0;
        var functions: usize = 0;
        var i: usize = 0;
        while (i + 16 < output.len) : (i += 1) {
            if (std.mem.eql(u8, output[i..][0..16], "export interface")) interfaces += 1;
            if (std.mem.eql(u8, output[i..][0..16], "export function ")) functions += 1;
            if (i + 11 <= output.len and std.mem.eql(u8, output[i..][0..11], "export type")) types += 1;
            if (i + 12 <= output.len and std.mem.eql(u8, output[i..][0..12], "export const")) consts += 1;
        }
        assert(interfaces == 35);
        assert(types == 13);
        assert(consts == 27);
        // 25 extern structs × 2 (read + write) = 50 serde functions
        assert(functions == 50);
    }
}
