const std = @import("std");
const assert = std.debug.assert;
const message = @import("message.zig");
const state_machine = @import("state_machine.zig");

const SM = state_machine.StateMachineType(state_machine.MemoryStorage);

const output = blk: {
    @setEvalBranchQuota(200000);
    var buf: [131072]u8 = undefined;
    var w = Writer{ .buf = &buf, .pos = 0 };

    w.raw(
        \\// Serde round-trip test — generated by `zig build codegen`.
        \\// Run: npx tsx generated/serde_test.generated.ts [seed]
        \\
        \\import {
        \\  readProduct, writeProduct,
        \\  readProductCollection, writeProductCollection,
        \\  readInventoryTransfer, writeInventoryTransfer,
        \\  readOrderItem, writeOrderItem,
        \\  readOrderRequest, writeOrderRequest,
        \\  readOrderCompletion, writeOrderCompletion,
        \\  readOrderResultItem, writeOrderResultItem,
        \\  readOrderResult, writeOrderResult,
        \\  readOrderSummary, writeOrderSummary,
        \\  readSearchQuery, writeSearchQuery,
        \\  readListParams, writeListParams,
        \\  readLoginCodeRequest, writeLoginCodeRequest,
        \\  readLoginVerification, writeLoginVerification,
        \\  readMessage, writeMessage,
        \\  type Product, type ProductCollection, type InventoryTransfer,
        \\  type OrderItem, type OrderRequest, type OrderCompletion,
        \\  type OrderResultItem, type OrderResult, type OrderSummary,
        \\  type SearchQuery, type ListParams, type LoginCodeRequest,
        \\  type LoginVerification, type Message,
        \\  type ProductFlags, type CollectionFlags,
        \\} from './types.generated.ts';
        \\
        \\function hexToBytes(hex: string): Uint8Array {
        \\  const bytes = new Uint8Array(hex.length / 2);
        \\  for (let i = 0; i < hex.length; i += 2)
        \\    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
        \\  return bytes;
        \\}
        \\
        \\function assertBytesEqual(a: Uint8Array, b: Uint8Array, label: string): void {
        \\  if (a.length !== b.length) throw new Error(`${label}: length ${a.length} !== ${b.length}`);
        \\  for (let i = 0; i < a.length; i++) {
        \\    if (a[i] !== b[i])
        \\      throw new Error(`${label}: byte ${i} differs: 0x${a[i].toString(16).padStart(2,'0')} !== 0x${b[i].toString(16).padStart(2,'0')}`);
        \\  }
        \\}
        \\
        \\// --- Seeded PRNG (mulberry32) ---
        \\
        \\function mulberry32(seed: number) {
        \\  let s = seed | 0;
        \\  return function(): number {
        \\    s = (s + 0x6D2B79F5) | 0;
        \\    let t = Math.imul(s ^ (s >>> 15), 1 | s);
        \\    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        \\    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
        \\  };
        \\}
        \\
        \\function randInt(rng: () => number, min: number, max: number): number {
        \\  return Math.floor(rng() * (max - min + 1)) + min;
        \\}
        \\
        \\function randHex(rng: () => number, bytes: number): string {
        \\  let s = '';
        \\  for (let i = 0; i < bytes * 2; i++) s += '0123456789abcdef'[randInt(rng, 0, 15)];
        \\  return s;
        \\}
        \\
        \\function randStr(rng: () => number, maxLen: number): string {
        \\  const len = randInt(rng, 0, maxLen);
        \\  let s = '';
        \\  for (let i = 0; i < len; i++) s += String.fromCharCode(randInt(rng, 0x20, 0x7e));
        \\  return s;
        \\}
        \\
        \\function randBytes(rng: () => number, len: number): Uint8Array {
        \\  const b = new Uint8Array(len);
        \\  for (let i = 0; i < len; i++) b[i] = randInt(rng, 0, 255);
        \\  return b;
        \\}
        \\
        \\function randFlags(rng: () => number): ProductFlags | CollectionFlags {
        \\  return { active: rng() > 0.5 };
        \\}
        \\
        \\let passed = 0;
        \\
        \\
    );

    // --- Test vectors: Zig-constructed structs → hex bytes ---
    // These test the cross-language boundary: bytes come from Zig's
    // memory layout, TS must decode and re-encode to matching bytes.

    w.raw("// --- Test vectors from Zig ---\n\n");

    w.emit_test_vector("Product", message.Product, test_product());
    w.emit_test_vector("ProductCollection", message.ProductCollection, test_collection());
    w.emit_test_vector("InventoryTransfer", message.InventoryTransfer, test_transfer());
    w.emit_test_vector("OrderItem", message.OrderItem, test_order_item());
    w.emit_test_vector("OrderRequest", message.OrderRequest, test_order_request());
    w.emit_test_vector("OrderCompletion", message.OrderCompletion, test_completion());
    w.emit_test_vector("OrderResultItem", message.OrderResultItem, test_result_item());
    w.emit_test_vector("OrderResult", message.OrderResult, test_order_result());
    w.emit_test_vector("OrderSummary", message.OrderSummary, test_order_summary());
    w.emit_test_vector("SearchQuery", message.SearchQuery, test_search_query());
    w.emit_test_vector("ListParams", message.ListParams, test_list_params());
    w.emit_test_vector("LoginCodeRequest", message.LoginCodeRequest, test_login_request());
    w.emit_test_vector("LoginVerification", message.LoginVerification, test_login_verify());
    w.emit_test_vector("Message", message.Message, test_message());

    // --- Random round-trip tests ---
    w.raw("// --- Random round-trip tests ---\n\n");
    w.raw("const seed = parseInt(process.argv[2]) || Date.now();\n");
    w.raw("const rng = mulberry32(seed);\n\n");

    w.emit_random_roundtrip("Product", message.Product);
    w.emit_random_roundtrip("ProductCollection", message.ProductCollection);
    w.emit_random_roundtrip("InventoryTransfer", message.InventoryTransfer);
    w.emit_random_roundtrip("OrderItem", message.OrderItem);
    w.emit_random_roundtrip("OrderRequest", message.OrderRequest);
    w.emit_random_roundtrip("OrderCompletion", message.OrderCompletion);
    w.emit_random_roundtrip("OrderResultItem", message.OrderResultItem);
    w.emit_random_roundtrip("OrderResult", message.OrderResult);
    w.emit_random_roundtrip("OrderSummary", message.OrderSummary);
    w.emit_random_roundtrip("SearchQuery", message.SearchQuery);
    w.emit_random_roundtrip("ListParams", message.ListParams);
    w.emit_random_roundtrip("LoginCodeRequest", message.LoginCodeRequest);
    w.emit_random_roundtrip("LoginVerification", message.LoginVerification);
    w.emit_random_roundtrip("Message", message.Message);

    w.raw("console.log(`${passed} serde round-trip tests passed (seed: ${seed})`);\n");

    assert(w.pos > 0);
    assert(w.pos < buf.len * 3 / 4);

    const final = buf[0..w.pos];
    break :blk final[0..final.len].*;
};

pub fn main() !void {
    try std.io.getStdOut().writer().writeAll(&output);
}

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

const Writer = struct {
    buf: *[131072]u8,
    pos: usize,

    fn raw(w: *Writer, s: []const u8) void {
        assert(w.pos + s.len <= w.buf.len);
        @memcpy(w.buf[w.pos..][0..s.len], s);
        w.pos += s.len;
    }

    fn int(w: *Writer, comptime n: comptime_int) void {
        w.raw(int_str(n));
    }

    fn hex(w: *Writer, comptime bytes: []const u8) void {
        const hex_chars = "0123456789abcdef";
        for (bytes) |b| {
            w.buf[w.pos] = hex_chars[b >> 4];
            w.buf[w.pos + 1] = hex_chars[b & 0xf];
            w.pos += 2;
        }
    }

    /// Emit a test vector: Zig struct → hex bytes → TS decode → re-encode → byte compare.
    fn emit_test_vector(w: *Writer, comptime name: []const u8, comptime T: type, comptime val: T) void {
        const bytes: [@sizeOf(T)]u8 = @bitCast(val);
        w.raw("{\n  const orig = hexToBytes('");
        w.hex(&bytes);
        w.raw("');\n");
        w.raw("  const decoded = read");
        w.raw(name);
        w.raw("(orig, 0);\n");
        w.raw("  const reEncoded = new Uint8Array(");
        w.int(@sizeOf(T));
        w.raw(");\n");
        w.raw("  write");
        w.raw(name);
        w.raw("(reEncoded, 0, decoded);\n");
        w.raw("  assertBytesEqual(orig, reEncoded, '");
        w.raw(name);
        w.raw(" test vector');\n");
        w.raw("  passed++;\n");
        w.raw("}\n\n");
    }

    /// Emit a random round-trip test block for one struct type.
    fn emit_random_roundtrip(w: *Writer, comptime name: []const u8, comptime T: type) void {
        w.raw("for (let _r = 0; _r < 100; _r++) {\n");
        w.raw("  const obj: ");
        w.raw(name);
        w.raw(" = ");
        w.emit_random_constructor(T);
        w.raw(";\n");
        w.raw("  const buf = new Uint8Array(");
        w.int(@sizeOf(T));
        w.raw(");\n");
        w.raw("  write");
        w.raw(name);
        w.raw("(buf, 0, obj);\n");
        w.raw("  const decoded = read");
        w.raw(name);
        w.raw("(buf, 0);\n");
        w.raw("  const buf2 = new Uint8Array(");
        w.int(@sizeOf(T));
        w.raw(");\n");
        w.raw("  write");
        w.raw(name);
        w.raw("(buf2, 0, decoded);\n");
        w.raw("  assertBytesEqual(buf, buf2, '");
        w.raw(name);
        w.raw(" random #' + _r);\n");
        w.raw("  passed++;\n");
        w.raw("}\n\n");
    }

    /// Emit a TS expression that creates a random instance of T.
    /// Wrapped in parens so arrow functions return object literals: () => ({...})
    fn emit_random_constructor(w: *Writer, comptime T: type) void {
        const info = @typeInfo(T).@"struct";
        w.raw("({\n");
        for (info.fields) |field| {
            if (should_skip(T, field.name)) continue;
            w.raw("    ");
            w.raw(field.name);
            w.raw(": ");
            w.emit_random_value(T, field);
            w.raw(",\n");
        }
        w.raw("  })");
    }

    /// Emit a TS expression for a random value of the field's type.
    fn emit_random_value(w: *Writer, comptime StructT: type, comptime field: std.builtin.Type.StructField) void {
        if (is_array_type(field.type)) {
            const arr = @typeInfo(field.type).array;
            if (arr.child != u8) {
                // [N]T array with _len → random-length array of random items
                w.raw("Array.from({ length: randInt(rng, 0, ");
                w.int(arr.len);
                w.raw(") }, () => ");
                w.emit_random_constructor(arr.child);
                w.raw(")");
            } else if (has_len_companion(StructT, field.name)) {
                // [N]u8 with _len → random ASCII string
                w.raw("randStr(rng, ");
                w.int(arr.len);
                w.raw(")");
            } else {
                // [N]u8 without _len → random bytes
                w.raw("randBytes(rng, ");
                w.int(arr.len);
                w.raw(")");
            }
            return;
        }
        const ft = @typeInfo(field.type);
        switch (ft) {
            .int => |i| {
                if (i.bits == 128) {
                    w.raw("randHex(rng, 16)");
                } else if (i.bits == 64) {
                    // Keep within safe integer range
                    w.raw("randInt(rng, 0, 2**32 - 1)");
                } else if (i.bits == 32) {
                    w.raw("randInt(rng, 0, 2**32 - 1)");
                } else if (i.bits == 16) {
                    w.raw("randInt(rng, 0, 65535)");
                } else {
                    w.raw("randInt(rng, 0, 255)");
                }
            },
            .@"enum" => {
                const fields = @typeInfo(field.type).@"enum".fields;
                w.raw("([");
                for (fields, 0..) |ef, j| {
                    if (j > 0) w.raw(", ");
                    w.raw("'");
                    w.raw(ef.name);
                    w.raw("'");
                }
                w.raw("] as const)[randInt(rng, 0, ");
                w.int(fields.len - 1);
                w.raw(")]");
            },
            .@"struct" => {
                // Packed flags
                w.raw("randFlags(rng)");
            },
            .bool => w.raw("rng() > 0.5"),
            else => @compileError("unhandled random type: " ++ @typeName(field.type)),
        }
    }
};

// ---------------------------------------------------------------------------
// Helpers (shared with codegen.zig)
// ---------------------------------------------------------------------------

fn int_str(comptime n: comptime_int) []const u8 {
    if (n == 0) return "0";
    var buf_local: [20]u8 = undefined;
    var pos: usize = 20;
    var val = if (n < 0) -n else n;
    while (val > 0) {
        pos -= 1;
        buf_local[pos] = @intCast('0' + val % 10);
        val = val / 10;
    }
    if (n < 0) {
        pos -= 1;
        buf_local[pos] = '-';
    }
    return buf_local[pos..20];
}

fn is_array_type(comptime T: type) bool {
    return @typeInfo(T) == .array;
}

fn has_field(comptime StructT: type, comptime name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, name)) return true;
    }
    return false;
}

fn has_len_companion(comptime StructT: type, comptime field_name: []const u8) bool {
    for (@typeInfo(StructT).@"struct".fields) |f| {
        if (f.name.len == field_name.len + 4 and
            std.mem.eql(u8, f.name[0..field_name.len], field_name) and
            std.mem.eql(u8, f.name[field_name.len..], "_len"))
        {
            return true;
        }
    }
    if (std.mem.eql(u8, field_name, "items") and has_field(StructT, "len")) {
        return true;
    }
    return false;
}

fn should_skip(comptime StructT: type, comptime field_name: []const u8) bool {
    if (std.mem.startsWith(u8, field_name, "reserved")) return true;
    if (std.mem.eql(u8, field_name, "padding")) return true;
    if (field_name.len > 4 and std.mem.eql(u8, field_name[field_name.len - 4 ..], "_len")) {
        const base = field_name[0 .. field_name.len - 4];
        if (has_field(StructT, base)) return true;
    }
    if (std.mem.eql(u8, field_name, "len") and has_field(StructT, "items")) return true;
    return false;
}

// ---------------------------------------------------------------------------
// Test vector constructors — one per extern struct with non-trivial values.
// ---------------------------------------------------------------------------

fn set_str(comptime buf: []u8, comptime s: []const u8) void {
    @memcpy(buf[0..s.len], s);
}

fn test_product() message.Product {
    var p = std.mem.zeroes(message.Product);
    p.id = 0x0102030405060708090a0b0c0d0e0f10;
    set_str(&p.name, "Tiger Shirt");
    p.name_len = 11;
    set_str(&p.description, "A fine shirt");
    p.description_len = 12;
    p.price_cents = 2999;
    p.inventory = 100;
    p.version = 3;
    p.flags = .{ .active = true };
    return p;
}

fn test_collection() message.ProductCollection {
    var c = std.mem.zeroes(message.ProductCollection);
    c.id = 0xaabbccdd11223344aabbccdd11223344;
    set_str(&c.name, "Summer Sale");
    c.name_len = 11;
    c.flags = .{ .active = true };
    return c;
}

fn test_transfer() message.InventoryTransfer {
    var t = std.mem.zeroes(message.InventoryTransfer);
    t.target_id = 0xdeadbeef00000000deadbeef00000000;
    t.quantity = 50;
    return t;
}

fn test_order_item() message.OrderItem {
    var i = std.mem.zeroes(message.OrderItem);
    i.product_id = 0x11111111222222223333333344444444;
    i.quantity = 3;
    return i;
}

fn test_order_request() message.OrderRequest {
    var r = std.mem.zeroes(message.OrderRequest);
    r.id = 0xaaaabbbbccccddddeeeeffffaaaabbbb;
    r.items[0] = test_order_item();
    r.items[1] = std.mem.zeroes(message.OrderItem);
    r.items[1].product_id = 0x55555555666666667777777788888888;
    r.items[1].quantity = 1;
    r.items_len = 2;
    return r;
}

fn test_completion() message.OrderCompletion {
    var c = std.mem.zeroes(message.OrderCompletion);
    set_str(&c.payment_ref, "ch_1234567890");
    c.payment_ref_len = 13;
    c.result = .confirmed;
    return c;
}

fn test_result_item() message.OrderResultItem {
    var i = std.mem.zeroes(message.OrderResultItem);
    i.product_id = 0x11111111222222223333333344444444;
    set_str(&i.name, "Tiger Shirt");
    i.name_len = 11;
    i.line_total_cents = 8997;
    i.price_cents = 2999;
    i.quantity = 3;
    return i;
}

fn test_order_result() message.OrderResult {
    var r = std.mem.zeroes(message.OrderResult);
    r.id = 0xaaaabbbbccccddddeeeeffffaaaabbbb;
    r.items[0] = test_result_item();
    r.items_len = 1;
    set_str(&r.payment_ref, "ch_1234567890");
    r.payment_ref_len = 13;
    r.total_cents = 8997;
    r.timeout_at = 1700000000;
    r.status = .confirmed;
    return r;
}

fn test_order_summary() message.OrderSummary {
    var s = std.mem.zeroes(message.OrderSummary);
    s.id = 0xaaaabbbbccccddddeeeeffffaaaabbbb;
    set_str(&s.payment_ref, "ch_test");
    s.payment_ref_len = 7;
    s.total_cents = 5999;
    s.timeout_at = 1700000060;
    s.items_len = 2;
    s.status = .pending;
    return s;
}

fn test_search_query() message.SearchQuery {
    var q = std.mem.zeroes(message.SearchQuery);
    set_str(&q.query, "tiger");
    q.query_len = 5;
    return q;
}

fn test_list_params() message.ListParams {
    var l = std.mem.zeroes(message.ListParams);
    l.cursor = 0x00000000000000000000000000000042;
    set_str(&l.name_prefix, "Tig");
    l.name_prefix_len = 3;
    l.price_min = 1000;
    l.price_max = 5000;
    l.active_filter = .active_only;
    return l;
}

fn test_login_request() message.LoginCodeRequest {
    var r = std.mem.zeroes(message.LoginCodeRequest);
    set_str(&r.email, "test@example.com");
    r.email_len = 16;
    return r;
}

fn test_login_verify() message.LoginVerification {
    var v = std.mem.zeroes(message.LoginVerification);
    set_str(&v.email, "test@example.com");
    v.email_len = 16;
    @memcpy(&v.code, "123456");
    return v;
}

fn test_message() message.Message {
    var m = std.mem.zeroes(message.Message);
    m.id = 0x0102030405060708090a0b0c0d0e0f10;
    m.user_id = 0xaabbccdd11223344aabbccdd11223344;
    m.op = 42;
    m.timestamp = 1700000000;
    m.operation = .create_product;
    set_str(m.credential[0..16], "session-cookie16");
    m.credential_len = 16;
    // Body: embed a test product
    const p = test_product();
    @memcpy(m.body[0..@sizeOf(message.Product)], std.mem.asBytes(&p));
    return m;
}
