#!/usr/bin/env python3
# Python adapter — reads the annotation manifest from the scanner,
# extracts handler module info, and generates handlers_generated.py.
#
# Usage: python adapters/python.py generated/manifest.json generated/handlers_generated.py <handlers-dir>
#
# Generates: handler imports, modules registry, route table.
# The CALL/RESULT protocol runtime (call_runtime.py) imports from
# the generated file. Pure data — no protocol code generated.

import json
import sys
from pathlib import Path


def to_snake_case(op: str) -> str:
    return op


def route_specificity(pattern: str) -> list[int]:
    if pattern == "/":
        return [0]
    return [0 if seg.startswith(":") else 1 for seg in pattern[1:].split("/")]


def main():
    if len(sys.argv) < 4:
        print("Usage: python adapters/python.py <manifest.json> <output.py> <handlers-dir>", file=sys.stderr)
        sys.exit(1)

    manifest_path = sys.argv[1]
    output_path = sys.argv[2]
    handlers_dir = sys.argv[3]

    with open(manifest_path) as f:
        manifest = json.load(f)

    # Build per-operation module map.
    operation_modules: dict[str, dict] = {}
    for ann in manifest["annotations"]:
        op = ann["operation"]
        if op not in operation_modules:
            operation_modules[op] = {
                "file": ann["file"],
                "module": to_snake_case(op),
            }

    # Build route table from match directives.
    route_table = []
    for ann in manifest["annotations"]:
        if ann["phase"] == "translate" and ann.get("route_match"):
            rm = ann["route_match"]
            route_table.append({
                "operation": ann["operation"],
                "method": rm["method"],
                "pattern": rm["pattern"],
                "query_params": rm.get("query_params", []),
            })

    # Sort by specificity.
    def sort_key(r):
        spec = route_specificity(r["pattern"])
        # method first, then longer patterns, then literals before params
        return (r["method"], [-len(spec)] + [-s for s in spec], r["operation"])

    route_table.sort(key=sort_key)

    # Resolve handlers_dir to an absolute path for the import.
    handlers_abs = str(Path(handlers_dir).resolve())

    # Generate output.
    out = f'''# Auto-generated by the Python adapter — do not edit.
#
# Handler imports, modules registry, and route table for the
# CALL/RESULT sidecar runtime. Generated from the annotation
# scanner's manifest.json.

import importlib.util
import sys
from pathlib import Path

HANDLERS_DIR = {handlers_abs!r}

def _load_module(name: str):
    """Load a handler module by name from the handlers directory."""
    path = Path(HANDLERS_DIR) / f"{{name}}.py"
    if not path.exists():
        return None
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        return None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

'''

    # Module loading.
    out += "# Handler modules — loaded from the handlers directory.\n"
    out += "modules = {\n"
    for op, mod_info in operation_modules.items():
        out += f"    {op!r}: _load_module({mod_info['module']!r}),\n"
    out += "}\n\n"

    # Route table.
    out += "route_table = [\n"
    for r in route_table:
        out += f"    {{'operation': {r['operation']!r}, 'method': {r['method']!r}, 'pattern': {r['pattern']!r}, 'query_params': {r['query_params']!r}}},\n"
    out += "]\n"

    with open(output_path, "w") as f:
        f.write(out)

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
