// TypeScript adapter — reads the annotation manifest from the scanner,
// extracts handler module info, and generates handlers.generated.ts.
//
// Usage: npx tsx adapters/typescript.ts generated/manifest.json generated/handlers.generated.ts
//
// Generates: handler imports, modules registry, route table.
// The CALL/RESULT protocol runtime (call_runtime.ts) imports from
// the generated file. Pure data — no protocol code generated.

import { readFileSync, writeFileSync } from "fs";

const manifestPath = process.argv[2];
const outputPath = process.argv[3];

if (!manifestPath || !outputPath) {
  console.error("Usage: npx tsx adapters/typescript.ts <manifest.json> <output.ts>");
  process.exit(1);
}

interface ManifestAnnotation {
  phase: "translate" | "prefetch" | "execute" | "render" | "worker";
  operation: string;
  file: string;
  line: number;
  route_match?: { method: string; pattern: string; query_params?: string[] };
  returns?: string;
}

// Read manifest.
const manifest: { annotations: ManifestAnnotation[] } = JSON.parse(
  readFileSync(manifestPath, "utf-8")
);

// Build per-operation module map: operation → { file, namespace }.
const operationModules = new Map<string, { file: string; namespace: string }>();

function toCamelCase(op: string): string {
  return op.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

for (const ann of manifest.annotations) {
  if (!operationModules.has(ann.operation)) {
    operationModules.set(ann.operation, {
      file: ann.file,
      namespace: toCamelCase(ann.operation),
    });
  }
}

// Build route table from match directives.
interface RouteEntry { operation: string; method: string; pattern: string; query_params: string[]; }
const routeTable: RouteEntry[] = [];
for (const ann of manifest.annotations) {
  if (ann.phase === "translate" && ann.route_match) {
    routeTable.push({
      operation: ann.operation,
      method: ann.route_match.method,
      pattern: ann.route_match.pattern,
      query_params: ann.route_match.query_params || [],
    });
  }
}

// Sort routes by specificity.
function routeSpecificity(pattern: string): number[] {
  if (pattern === "/") return [0];
  return pattern.slice(1).split("/").map(seg =>
    seg.startsWith(":") ? 0 : 1
  );
}

routeTable.sort((a, b) => {
  if (a.method !== b.method) return a.method < b.method ? -1 : 1;
  const specA = routeSpecificity(a.pattern);
  const specB = routeSpecificity(b.pattern);
  if (specA.length !== specB.length) return specB.length - specA.length;
  for (let i = 0; i < specA.length; i++) {
    if (specA[i] !== specB[i]) return specB[i] - specA[i];
  }
  return a.operation < b.operation ? -1 : 1;
});

// Generate output.
let out = `// Auto-generated by the TypeScript adapter — do not edit.
//
// Handler imports, modules registry, and route table for the
// CALL/RESULT sidecar runtime. Generated from the annotation
// scanner's manifest.json.

`;

// Namespace imports.
for (const [_op, mod] of operationModules) {
  const relative = "../" + mod.file;
  out += `import * as ${mod.namespace} from '${relative}';\n`;
}

out += `
export interface HandlerModule {
  route?: (req: any) => any | null;
  prefetch?: (msg: any, db: any) => any;
  handle?: (ctx: any, db: any) => string;
  render?: (ctx: any, db?: any) => string;
}

export const modules: Record<string, HandlerModule> = {\n`;
for (const [op, mod] of operationModules) {
  out += `  ${op}: ${mod.namespace},\n`;
}
out += `};

export interface RouteTableEntry {
  operation: string;
  method: string;
  pattern: string;
  query_params: string[];
}

export const routeTable: RouteTableEntry[] = [\n`;
for (const r of routeTable) {
  const qp = r.query_params.length > 0
    ? `[${r.query_params.map((q: string) => `'${q}'`).join(', ')}]`
    : `[]`;
  out += `  { operation: '${r.operation}', method: '${r.method}', pattern: '${r.pattern}', query_params: ${qp} },\n`;
}
out += `];\n`;

// Worker functions — one entry per [worker] annotation.
const workerAnnotations = manifest.annotations.filter(a => a.phase === "worker");
if (workerAnnotations.length > 0) {
  // Ensure worker modules are imported.
  for (const ann of workerAnnotations) {
    if (!operationModules.has(ann.operation)) {
      operationModules.set(ann.operation, {
        file: ann.file,
        namespace: toCamelCase(ann.operation),
      });
      const relative = "../" + ann.file;
      // Import already emitted above if the file has other phases.
      // Check if we need to add it.
      if (!out.includes(`import * as ${toCamelCase(ann.operation)}`)) {
        // Prepend import (insert after the first newline in the generated section).
        const importLine = `import * as ${toCamelCase(ann.operation)} from '${relative}';\n`;
        const insertPos = out.indexOf('\n') + 1;
        out = out.slice(0, insertPos) + importLine + out.slice(insertPos);
      }
    }
  }

  out += `
export interface WorkerFunction {
  fn: (...args: any[]) => Promise<any>;
  returns: string;
}

export const workerFunctions: Record<string, WorkerFunction> = {\n`;
  for (const ann of workerAnnotations) {
    const ns = toCamelCase(ann.operation);
    out += `  ${ann.operation}: { fn: ${ns}.${ann.operation}, returns: '${ann.returns || ''}' },\n`;
  }
  out += `};\n`;
}

writeFileSync(outputPath, out);
console.log(`Generated: ${outputPath}`);
