// TypeScript adapter — reads the annotation manifest from the scanner,
// extracts function names from source files, and generates the dispatch.
//
// Usage: npx tsx adapters/typescript.ts generated/manifest.json generated/dispatch.generated.ts
//
// New protocol: JSON length-prefixed frames over unix socket.
// Four handler phases: route, prefetch, handle, render.
// Prefetch is declarative SQL — sidecar sends queries, framework executes.
// Handle queues writes via db.execute() — SQL sent back to framework.
// No binary serde. No PrefetchCache. No WriteSlot.

import { readFileSync, writeFileSync } from "fs";

const manifestPath = process.argv[2];
const outputPath = process.argv[3];

if (!manifestPath || !outputPath) {
  console.error("Usage: npx tsx adapters/typescript.ts <manifest.json> <output.ts>");
  process.exit(1);
}

interface ManifestAnnotation {
  phase: "translate" | "prefetch" | "execute" | "render";
  operation: string;
  file: string;
  line: number;
}

interface ResolvedAnnotation extends ManifestAnnotation {
  func_name: string;
}

// Read manifest.
const manifest: { annotations: ManifestAnnotation[] } = JSON.parse(
  readFileSync(manifestPath, "utf-8")
);

// Extract function names from source files.
const resolved: ResolvedAnnotation[] = [];

for (const ann of manifest.annotations) {
  const lines = readFileSync(ann.file, "utf-8").split("\n");
  let codeLine: string | null = null;
  for (let i = ann.line; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "") continue;
    if (line.startsWith("//") || line.startsWith("#") || line.startsWith("--")) continue;
    codeLine = lines[i];
    break;
  }

  if (!codeLine) {
    console.error(`error: ${ann.file}:${ann.line}: no code line found after annotation`);
    process.exit(1);
  }

  const funcName = extractFuncName(codeLine);
  if (!funcName) {
    console.error(`error: ${ann.file}:${ann.line}: cannot extract function name from: ${codeLine.trim()}`);
    process.exit(1);
  }

  resolved.push({ ...ann, func_name: funcName });
}

function extractFuncName(line: string): string | null {
  const trimmed = line.trim();
  const funcMatch = trimmed.match(
    /^(?:export\s+)?(?:async\s+)?function\s+([a-zA-Z_]\w*)/
  );
  if (funcMatch) return funcMatch[1];
  const constMatch = trimmed.match(/^(?:export\s+)?const\s+([a-zA-Z_]\w*)/);
  if (constMatch) return constMatch[1];
  return null;
}

// Build per-operation module map: operation → { file, namespace }.
// Each handler file exports route/prefetch/handle/render with the same names,
// so we use namespace imports (import * as X from '...') to avoid collisions.
const operationModules = new Map<string, { file: string; namespace: string }>();

function toCamelCase(op: string): string {
  return op.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

for (const ann of resolved) {
  if (!operationModules.has(ann.operation)) {
    operationModules.set(ann.operation, {
      file: ann.file,
      namespace: toCamelCase(ann.operation),
    });
  }
}

// Build dispatch tables per phase.
const phases = ["translate", "prefetch", "execute", "render"] as const;
const tables: Record<string, Map<string, string>> = {};
for (const phase of phases) {
  tables[phase] = new Map();
  for (const ann of resolved.filter((a) => a.phase === phase)) {
    const mod = operationModules.get(ann.operation)!;
    tables[phase].set(ann.operation, `${mod.namespace}.${ann.func_name}`);
  }
}

// Generate output.
let out = `// Auto-generated by the TypeScript adapter — do not edit.
//
// Sidecar dispatch — JSON length-prefixed protocol over unix socket.
// Four handler phases: route → prefetch → handle → render.
// Framework pre-matches routes. Prefetch is declarative SQL.
// Handle queues writes via db.execute().

import * as net from 'net';
import { unlinkSync } from 'fs';

`;

// Namespace imports — one per operation handler file.
for (const [_op, mod] of operationModules) {
  const relative = "../" + mod.file;
  out += `import * as ${mod.namespace} from '${relative}';\n`;
}

out += "\n";

// Dispatch tables.
for (const phase of phases) {
  const tableName = phase === "translate" ? "routeHandlers"
    : phase === "prefetch" ? "prefetchHandlers"
    : phase === "execute" ? "handleHandlers"
    : "renderHandlers";
  out += `const ${tableName}: Record<string, Function> = {\n`;
  for (const [op, funcName] of tables[phase]) {
    out += `  '${op}': ${funcName},\n`;
  }
  out += "};\n\n";
}

// Socket server with JSON length-prefixed protocol.
out += `// --- JSON length-prefixed protocol ---
// Wire format: [4-byte BE length][JSON payload]
// Per-request exchange:
//   1. Route:   framework sends route_request → sidecar sends route_response
//   2. Execute: framework sends execute_request
//      → sidecar sends prefetch_queries
//      → framework sends prefetch_results
//      → sidecar sends handle_render_result

function sendFrame(conn: net.Socket, obj: object): void {
  const json = JSON.stringify(obj);
  const buf = Buffer.alloc(4 + Buffer.byteLength(json));
  buf.writeUInt32BE(Buffer.byteLength(json), 0);
  buf.write(json, 4);
  conn.write(buf);
}

interface WriteEntry {
  sql: string;
  params: unknown[];
}

const socketPath = process.argv[2];
if (!socketPath) { console.error('Usage: node dispatch.generated.ts <socket-path>'); process.exit(1); }

const server = net.createServer((conn) => {
  console.log('[sidecar] client connected');
  let pending = Buffer.alloc(0);

  // State machine for the execute exchange (prefetch → handle → render).
  let executeState: {
    operation: string;
    id: string;
    body: Record<string, any>;
    is_sse: boolean;
    prefetchKeys: string[];
  } | null = null;

  function processFrames(): void {
    while (pending.length >= 4) {
      const frameLen = pending.readUInt32BE(0);
      if (pending.length < 4 + frameLen) break;
      const json = pending.subarray(4, 4 + frameLen).toString('utf-8');
      pending = pending.subarray(4 + frameLen);
      let msg: any;
      try { msg = JSON.parse(json); } catch (e) {
        console.error('[sidecar] malformed JSON frame:', (e as Error).message);
        conn.destroy();
        return;
      }
      handleMessage(msg);
    }
  }

  function handleMessage(msg: any): void {
    switch (msg.tag) {
      case 'route': {
        // Try each route handler until one matches.
        let result: any = null;
        for (const handler of Object.values(routeHandlers)) {
          const r = handler(msg);
          if (r !== null) { result = r; break; }
        }
        if (result) {
          sendFrame(conn, { found: true, operation: result.operation, id: result.id, body: result.body || {} });
        } else {
          sendFrame(conn, { found: false });
        }
        break;
      }

      case 'execute': {
        // Phase 1: call prefetch handler to get SQL declarations.
        const prefetchFn = prefetchHandlers[msg.operation];
        const queries = prefetchFn ? prefetchFn(msg) : {};
        executeState = {
          operation: msg.operation,
          id: msg.id,
          body: msg.body || {},
          is_sse: msg.is_sse || false,
          prefetchKeys: Object.keys(queries),
        };
        // Send prefetch queries to framework for execution.
        sendFrame(conn, { tag: 'prefetch_queries', queries });
        break;
      }

      case 'prefetch_results': {
        if (!executeState) {
          console.error('[sidecar] prefetch_results without execute');
          conn.destroy();
          return;
        }
        const { operation, id, body, is_sse } = executeState;
        executeState = null;

        // Build handle context.
        const prefetched = msg.results || {};
        const ctx = { operation, id, prefetched, body };

        // Phase 2: call handle — may queue writes via db.execute().
        const writes: WriteEntry[] = [];
        const db = {
          execute(sql: string, params: unknown[]): void {
            writes.push({ sql, params });
          },
        };

        const handleFn = handleHandlers[operation];
        const status: string = handleFn ? handleFn(ctx, db) : 'ok';

        // Phase 3: call render.
        const renderCtx = { ...ctx, status, is_sse };
        const renderFn = renderHandlers[operation];
        const html: string = renderFn ? renderFn(renderCtx) : '';

        sendFrame(conn, { tag: 'result', status, writes, html });
        break;
      }

      default:
        console.error('[sidecar] unknown tag:', msg.tag);
        conn.destroy();
    }
  }

  conn.on('data', (chunk: Buffer) => {
    pending = Buffer.concat([pending, chunk]);
    processFrames();
  });
  conn.on('close', () => console.log('[sidecar] client disconnected'));
  conn.on('error', (err: Error) => console.error('[sidecar] error:', err.message));
});

try { unlinkSync(socketPath); } catch {}
server.listen(socketPath, () => console.log(\`[sidecar] listening on \${socketPath}\`));
process.on('SIGINT', () => { server.close(); process.exit(0); });
`;

writeFileSync(outputPath, out);
console.log(`Generated: ${outputPath}`);
