// TypeScript adapter — reads the annotation manifest from the scanner,
// extracts function names from source files, and generates the dispatch.
//
// Usage: npx tsx adapters/typescript.ts generated/manifest.json generated/dispatch.generated.ts
//
// This is the TypeScript-specific half of the adapter system. The scanner
// (Zig, language-agnostic) validates exhaustiveness and outputs the manifest.
// This adapter (TypeScript-specific) handles function name extraction and
// dispatch generation.

import { readFileSync, writeFileSync } from "fs";

const manifestPath = process.argv[2];
const outputPath = process.argv[3];

if (!manifestPath || !outputPath) {
  console.error("Usage: npx tsx adapters/typescript.ts <manifest.json> <output.ts>");
  process.exit(1);
}

interface ManifestAnnotation {
  phase: "translate" | "execute" | "render";
  operation: string;
  file: string;
  line: number;
}

interface ResolvedAnnotation extends ManifestAnnotation {
  func_name: string;
}

// Read manifest.
const manifest: { annotations: ManifestAnnotation[] } = JSON.parse(
  readFileSync(manifestPath, "utf-8")
);

// Extract function names from source files.
const resolved: ResolvedAnnotation[] = [];

for (const ann of manifest.annotations) {
  const lines = readFileSync(ann.file, "utf-8").split("\n");
  // The code line is right after the annotation line.
  // Find the next non-empty, non-comment line after ann.line.
  let codeLine: string | null = null;
  for (let i = ann.line; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "") continue;
    if (line.startsWith("//") || line.startsWith("#") || line.startsWith("--")) continue;
    codeLine = lines[i];
    break;
  }

  if (!codeLine) {
    console.error(`error: ${ann.file}:${ann.line}: no code line found after annotation`);
    process.exit(1);
  }

  const funcName = extractFuncName(codeLine);
  if (!funcName) {
    console.error(`error: ${ann.file}:${ann.line}: cannot extract function name from: ${codeLine.trim()}`);
    process.exit(1);
  }

  resolved.push({ ...ann, func_name: funcName });
}

// Extract function/export name from a TypeScript code line.
function extractFuncName(line: string): string | null {
  const trimmed = line.trim();

  // export function NAME(, export async function NAME(
  const funcMatch = trimmed.match(
    /^(?:export\s+)?(?:async\s+)?function\s+([a-zA-Z_]\w*)/
  );
  if (funcMatch) return funcMatch[1];

  // export const NAME =
  const constMatch = trimmed.match(/^(?:export\s+)?const\s+([a-zA-Z_]\w*)/);
  if (constMatch) return constMatch[1];

  return null;
}

// Generate dispatch file.
const imports = new Map<string, Set<string>>(); // file → set of func names

for (const ann of resolved) {
  if (!imports.has(ann.file)) imports.set(ann.file, new Set());
  imports.get(ann.file)!.add(ann.func_name);
}

let out = `// Auto-generated by the TypeScript adapter — do not edit.

import * as net from 'net';
import { unlinkSync } from 'fs';
import {
  readTranslateRequest, writeTranslateResponse,
  readExecuteRenderRequest, writeExecuteRenderResponse,
  translate_request_size, translate_response_size,
  execute_render_request_size, execute_render_response_size,
  TagValues,
  type TranslateRequest, type TranslateResponse,
  type ExecuteRenderRequest, type ExecuteRenderResponse,
} from './types.generated.ts';

`;

// Import annotated functions.
for (const [file, funcs] of imports) {
  const relative = "../" + file;
  out += `import { ${[...funcs].join(", ")} } from '${relative}';\n`;
}

out += "\n";

// Dispatch tables.
for (const phase of ["translate", "execute", "render"] as const) {
  out += `const ${phase}Handlers: Record<string, Function> = {\n`;
  for (const ann of resolved.filter((a) => a.phase === phase)) {
    out += `  '${ann.operation}': ${ann.func_name},\n`;
  }
  out += "};\n\n";
}

// Socket server.
// No default handlers — the scanner validated exhaustiveness.
// If a handler is missing, the property access throws. This is
// a configuration error (adapter bug or scanner bypass), not a
// runtime condition to handle gracefully.
out += `const socketPath = process.argv[2];
if (!socketPath) { console.error('Usage: node dispatch.generated.ts <socket-path>'); process.exit(1); }

const server = net.createServer((conn) => {
  console.log('[sidecar] client connected');
  let pending = Buffer.alloc(0);
  conn.on('data', (chunk: Buffer) => {
    pending = Buffer.concat([pending, chunk]);
    while (pending.length > 0) {
      const tag = pending[0];
      if (tag === TagValues.translate) {
        if (pending.length < translate_request_size) break;
        const req = readTranslateRequest(new Uint8Array(pending.buffer, pending.byteOffset, translate_request_size), 0);
        pending = pending.subarray(translate_request_size);
        // Translate: try each handler until one returns found=1.
        // Unlike execute/render, translate determines the operation — we
        // can't dispatch by operation name because we don't know it yet.
        //
        // O(n) per request: 24 handlers × ~40ns each ≈ 1μs. The socket
        // round trip is ~50μs — iteration is 2% overhead. At 20,000
        // ops/sec (socket limit), adds 20ms/sec total CPU. The socket
        // becomes the bottleneck long before the iteration does.
        //
        // A generated URL router would be faster but language-specific
        // (pattern matching varies by language). The iteration keeps the
        // adapter simple and language-agnostic in structure.
        let resp: TranslateResponse = { id: '0'.repeat(32), body: new Uint8Array(672), found: 0, operation: 'root' };
        for (const handler of Object.values(translateHandlers)) {
          const result = handler(req);
          if (result.found === 1) { resp = result; break; }
        }
        const out = new Uint8Array(translate_response_size);
        writeTranslateResponse(out, 0, resp);
        conn.write(out);
      } else if (tag === TagValues.execute_render) {
        if (pending.length < execute_render_request_size) break;
        const req = readExecuteRenderRequest(new Uint8Array(pending.buffer, pending.byteOffset, execute_render_request_size), 0);
        pending = pending.subarray(execute_render_request_size);
        const execResult = executeHandlers[req.operation](req.cache, req.body);
        const html = renderHandlers[req.operation](req.operation, execResult.status, execResult);
        const resp: ExecuteRenderResponse = {
          status: execResult.status,
          writes_len: 0, result_tag: 0,
          result: new Uint8Array(47248),
          writes: Array.from({ length: 21 }, () => ({ tag: 0, reserved_tag: new Uint8Array(15), data: new Uint8Array(3632) })),
          html,
          tail_reserved: new Uint8Array(3),
        };
        const respBytes = new Uint8Array(execute_render_response_size);
        writeExecuteRenderResponse(respBytes, 0, resp);
        conn.write(respBytes);
      } else {
        console.error('[sidecar] unknown tag:', tag);
        conn.destroy();
        return;
      }
    }
  });
  conn.on('close', () => console.log('[sidecar] client disconnected'));
  conn.on('error', (err: Error) => console.error('[sidecar] error:', err.message));
});

try { unlinkSync(socketPath); } catch {}
server.listen(socketPath, () => console.log(\`[sidecar] listening on \${socketPath}\`));
process.on('SIGINT', () => { server.close(); process.exit(0); });
`;

writeFileSync(outputPath, out);
console.log(`Generated: ${outputPath}`);
