// Auto-generated by the TypeScript adapter — do not edit.
//
// Handler imports, modules registry, and route table for the
// CALL/RESULT sidecar runtime. Generated from the annotation
// scanner's manifest.json.

import * as addCollectionMember from '../handlers/add_collection_member.ts';
import * as cancelOrder from '../handlers/cancel_order.ts';
import * as chargePayment from '../handlers/charge_payment.ts';
import * as completeOrder from '../handlers/complete_order.ts';
import * as createOrder from '../handlers/create_order.ts';
import * as createProduct from '../handlers/create_product.ts';
import * as deleteCollection from '../handlers/delete_collection.ts';
import * as deleteProduct from '../handlers/delete_product.ts';
import * as getCollection from '../handlers/get_collection.ts';
import * as getOrder from '../handlers/get_order.ts';
import * as getProduct from '../handlers/get_product.ts';
import * as getProductInventory from '../handlers/get_product_inventory.ts';
import * as listCollections from '../handlers/list_collections.ts';
import * as listOrders from '../handlers/list_orders.ts';
import * as listProducts from '../handlers/list_products.ts';
import * as logout from '../handlers/logout.ts';
import * as pageLoadDashboard from '../handlers/page_load_dashboard.ts';
import * as pageLoadLogin from '../handlers/page_load_login.ts';
import * as processImage from '../handlers/process_image.ts';
import * as removeCollectionMember from '../handlers/remove_collection_member.ts';
import * as requestLoginCode from '../handlers/request_login_code.ts';
import * as searchProducts from '../handlers/search_products.ts';
import * as sendOrderEmail from '../handlers/send_order_email.ts';
import * as transferInventory from '../handlers/transfer_inventory.ts';
import * as updateProduct from '../handlers/update_product.ts';
import * as verifyLoginCode from '../handlers/verify_login_code.ts';

export interface HandlerModule {
  route?: (req: any) => any | null;
  prefetch?: (msg: any, db: any) => any;
  handle?: (ctx: any, db: any) => string;
  render?: (ctx: any, db?: any) => string;
}

export const modules: Record<string, HandlerModule> = {
  add_collection_member: addCollectionMember,
  cancel_order: cancelOrder,
  charge_payment: chargePayment,
  complete_order: completeOrder,
  create_order: createOrder,
  create_product: createProduct,
  delete_collection: deleteCollection,
  delete_product: deleteProduct,
  get_collection: getCollection,
  get_order: getOrder,
  get_product: getProduct,
  get_product_inventory: getProductInventory,
  list_collections: listCollections,
  list_orders: listOrders,
  list_products: listProducts,
  logout: logout,
  page_load_dashboard: pageLoadDashboard,
  page_load_login: pageLoadLogin,
  process_image: processImage,
  remove_collection_member: removeCollectionMember,
  request_login_code: requestLoginCode,
  search_products: searchProducts,
  send_order_email: sendOrderEmail,
  transfer_inventory: transferInventory,
  update_product: updateProduct,
  verify_login_code: verifyLoginCode,
};

export interface RouteTableEntry {
  operation: string;
  method: string;
  pattern: string;
  query_params: string[];
}

export const routeTable: RouteTableEntry[] = [
  { operation: 'remove_collection_member', method: 'delete', pattern: '/collections/:id/members/:sub_id', query_params: [] },
  { operation: 'delete_collection', method: 'delete', pattern: '/collections/:id', query_params: [] },
  { operation: 'delete_product', method: 'delete', pattern: '/products/:id', query_params: [] },
  { operation: 'get_product_inventory', method: 'get', pattern: '/products/:id/inventory', query_params: [] },
  { operation: 'get_collection', method: 'get', pattern: '/collections/:id', query_params: [] },
  { operation: 'get_order', method: 'get', pattern: '/orders/:id', query_params: [] },
  { operation: 'get_product', method: 'get', pattern: '/products/:id', query_params: [] },
  { operation: 'list_collections', method: 'get', pattern: '/collections', query_params: [] },
  { operation: 'list_orders', method: 'get', pattern: '/orders', query_params: [] },
  { operation: 'list_products', method: 'get', pattern: '/products', query_params: ['q'] },
  { operation: 'page_load_login', method: 'get', pattern: '/login', query_params: [] },
  { operation: 'search_products', method: 'get', pattern: '/products', query_params: ['q'] },
  { operation: 'page_load_dashboard', method: 'get', pattern: '/', query_params: [] },
  { operation: 'transfer_inventory', method: 'post', pattern: '/products/:id/transfer-inventory/:sub_id', query_params: [] },
  { operation: 'add_collection_member', method: 'post', pattern: '/collections/:id/members', query_params: [] },
  { operation: 'cancel_order', method: 'post', pattern: '/orders/:id/cancel', query_params: [] },
  { operation: 'complete_order', method: 'post', pattern: '/orders/:id/complete', query_params: [] },
  { operation: 'request_login_code', method: 'post', pattern: '/login/request', query_params: [] },
  { operation: 'verify_login_code', method: 'post', pattern: '/login/verify', query_params: [] },
  { operation: 'create_order', method: 'post', pattern: '/orders', query_params: [] },
  { operation: 'create_product', method: 'post', pattern: '/products', query_params: [] },
  { operation: 'logout', method: 'post', pattern: '/logout', query_params: [] },
  { operation: 'update_product', method: 'put', pattern: '/products/:id', query_params: [] },
];

export interface PrefetchKeyInfo { key: string; mode: "query" | "queryAll"; }
export const prefetchKeyMap: Record<string, PrefetchKeyInfo[]> = {"add_collection_member":[{"key":"collection","mode":"query"}],"cancel_order":[{"key":"order","mode":"query"}],"complete_order":[{"key":"order","mode":"query"}],"create_product":[{"key":"existing","mode":"query"}],"delete_collection":[{"key":"collection","mode":"query"}],"delete_product":[{"key":"product","mode":"query"}],"get_collection":[{"key":"collection","mode":"query"}],"get_order":[{"key":"order","mode":"query"}],"get_product":[{"key":"product","mode":"query"}],"get_product_inventory":[{"key":"product","mode":"query"}],"list_collections":[{"key":"collections","mode":"queryAll"}],"list_orders":[{"key":"orders","mode":"queryAll"}],"list_products":[{"key":"products","mode":"queryAll"}],"page_load_dashboard":[{"key":"products","mode":"queryAll"},{"key":"collections","mode":"queryAll"},{"key":"orders","mode":"queryAll"}],"remove_collection_member":[{"key":"collection","mode":"query"}],"search_products":[{"key":"results","mode":"queryAll"}],"transfer_inventory":[{"key":"source","mode":"query"},{"key":"target","mode":"query"}],"update_product":[{"key":"product","mode":"query"}],"verify_login_code":[{"key":"login_code","mode":"query"}]};

// Generated from operations.json — always includes new operations.
export const OperationValues: Record<string, number> = {"root":0,"delete_product":1,"create_order":2,"charge_payment":3,"complete_order":4,"remove_collection_member":5,"get_product_inventory":6,"send_order_email":7,"get_order":8,"verify_login_code":9,"request_login_code":10,"search_products":11,"cancel_order":12,"list_orders":13,"list_products":14,"add_collection_member":15,"page_load_dashboard":16,"list_collections":17,"get_product":18,"logout":19,"get_collection":20,"delete_collection":21,"create_collection":22,"page_load_login":23,"create_product":24,"process_image":25,"transfer_inventory":26,"update_product":27};
export type Operation = "delete_product" | "create_order" | "charge_payment" | "complete_order" | "remove_collection_member" | "get_product_inventory" | "send_order_email" | "get_order" | "verify_login_code" | "request_login_code" | "search_products" | "cancel_order" | "list_orders" | "list_products" | "add_collection_member" | "page_load_dashboard" | "list_collections" | "get_product" | "logout" | "get_collection" | "delete_collection" | "create_collection" | "page_load_login" | "create_product" | "process_image" | "transfer_inventory" | "update_product";

export interface WorkerFunction {
  fn: (...args: any[]) => Promise<any>;
  returns: string;
}

export const workerFunctions: Record<string, WorkerFunction> = {
  charge_payment: { fn: chargePayment.charge_payment, returns: '' },
  process_image: { fn: processImage.process_image, returns: '' },
  send_order_email: { fn: sendOrderEmail.send_order_email, returns: '' },
};
