// Auto-generated by annotation scanner — do not edit.
//
// Comptime route table from // match directives. Single source of truth
// for Zig routing. Handlers declare routes via annotations only.
// Sorted by specificity: literal segments before param, longer before shorter.

const message = @import("../message.zig");
const http = @import("../framework/http.zig");

pub const Route = struct {
    operation: message.Operation,
    method: http.Method,
    pattern: []const u8,
    query_params: []const []const u8,
    handler: type,
};

pub const routes = [_]Route{
};

// Comptime assertions — validate routes that exist.
// Exhaustiveness (every operation has a route) is NOT checked here —
// sidecar operations have no native routes and go through 2-RT.
// The scanner validates exhaustiveness at build time.
comptime {
    // Assert: path params + query params fit in RouteParams for every route.
    const parse = @import("../framework/parse.zig");
    for (routes) |r| {
        const path_params = parse.count_params(r.pattern);
        const total = path_params + r.query_params.len;
        if (total > parse.max_route_params) {
            @compileError("route " ++ r.pattern ++ " has too many params (path + query)");
        }
    }

    // Assert: Method enum values match the cross-language contract
    // (method_vectors.json). If someone adds/reorders enum variants,
    // this fires — update method_vectors.json and re-verify all languages.
    const assert = @import("std").debug.assert;
    assert(@intFromEnum(http.Method.get) == 0);
    assert(@intFromEnum(http.Method.put) == 1);
    assert(@intFromEnum(http.Method.post) == 2);
    assert(@intFromEnum(http.Method.delete) == 3);
    assert(@typeInfo(http.Method).@"enum".fields.len == 4);
}

// Shared route patterns are allowed — handlers disambiguate at runtime
// (e.g., GET /products: list vs search based on ?q= query param).
// Runtime assertion in translate() catches true duplicates (two handlers
// both claiming the same request). This is correct REST design: filtering
// a collection by query param is the same endpoint, not a sub-resource.
