// Cross-language protocol vector tests — validates TS serde and frame
// parsing against committed binary vectors generated by protocol.zig.
//
// These tests prove the TypeScript protocol implementation agrees with
// the Zig implementation byte-for-byte. Any drift is caught here.
//
// Run: npx tsx packages/ts/test/protocol_test.ts
// Prereq: zig build unit-test (generates packages/vectors/*.bin)

import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readRowSet, TypeTag, frame_max, columns_max, column_name_max, cell_value_max } from "../src/serde.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const vectorsDir = resolve(__dirname, "../../vectors");

let passed = 0;

function assert(condition: boolean, msg: string): void {
  if (!condition) { console.error(`FAIL: ${msg}`); process.exit(1); }
}

function assertEq(actual: unknown, expected: unknown, msg: string): void {
  if (actual !== expected) { console.error(`FAIL: ${msg}: expected ${expected}, got ${actual}`); process.exit(1); }
}

// =====================================================================
// 1. Row set vector (packages/vectors/row_sets.bin)
// =====================================================================
{
  const vectorPath = resolve(vectorsDir, "row_sets.bin");
  assert(existsSync(vectorPath), "row_sets.bin exists");
  const fileBytes = readFileSync(vectorPath);
  const buf = new DataView(fileBytes.buffer, fileBytes.byteOffset, fileBytes.byteLength);
  const { result } = readRowSet(buf, 0);

  // 5 columns: id, name, price, data, score
  assertEq(result.columns.length, 5, "rowset: col count");
  assertEq(result.columns[0].name, "id", "rowset: col 0");
  assertEq(result.columns[1].name, "name", "rowset: col 1");
  assertEq(result.columns[2].name, "price", "rowset: col 2");
  assertEq(result.columns[3].name, "data", "rowset: col 3");
  assertEq(result.columns[4].name, "score", "rowset: col 4");

  // 2 rows
  assertEq(result.rows.length, 2, "rowset: row count");

  // Row 1: id=42, name="Widget", price=-1, data=[0xDE,0xAD], score=3.14
  assertEq(result.rows[0].id, 42, "rowset: r0 id");
  assertEq(result.rows[0].name, "Widget", "rowset: r0 name");
  assertEq(result.rows[0].price, -1, "rowset: r0 price");
  const blob0 = result.rows[0].data as Uint8Array;
  assertEq(blob0.length, 2, "rowset: r0 data len");
  assertEq(blob0[0], 0xDE, "rowset: r0 data[0]");
  assertEq(blob0[1], 0xAD, "rowset: r0 data[1]");
  assertEq(result.rows[0].score, 3.14, "rowset: r0 score");

  // Row 2: id=0, name="", price=999, data=[], score=-0.0
  assertEq(result.rows[1].id, 0, "rowset: r1 id");
  assertEq(result.rows[1].name, "", "rowset: r1 name");
  assertEq(result.rows[1].price, 999, "rowset: r1 price");
  const blob1 = result.rows[1].data as Uint8Array;
  assertEq(blob1.length, 0, "rowset: r1 data len");
  assert(Object.is(result.rows[1].score, -0), "rowset: r1 score is -0");

  passed++;
  console.log("  Row set vector: OK");
}

// =====================================================================
// 2. CALL/RESULT/QUERY/QUERY_RESULT frame vector (packages/vectors/frames.bin)
// =====================================================================
{
  const vectorPath = resolve(vectorsDir, "frames.bin");
  assert(existsSync(vectorPath), "frames.bin exists");
  const data = readFileSync(vectorPath);
  const dv = new DataView(data.buffer, data.byteOffset, data.byteLength);
  let pos = 0;

  const frameCount = data[pos]; pos += 1;
  assertEq(frameCount, 4, "frames: count");

  function readFrame(): { payload: Uint8Array; dv: DataView } {
    const len = dv.getUint32(pos, false); pos += 4;
    const payload = new Uint8Array(data.buffer, data.byteOffset + pos, len);
    pos += len;
    return { payload, dv: new DataView(payload.buffer, payload.byteOffset, payload.byteLength) };
  }

  // Frame 0: CALL — request_id=1, name="prefetch", args=[op=0x14, id=0x01..0x10]
  {
    const { payload, dv: fdv } = readFrame();
    assertEq(payload[0], 0x10, "CALL: tag");
    assertEq(fdv.getUint32(1, false), 1, "CALL: request_id");
    const nameLen = fdv.getUint16(5, false);
    assertEq(nameLen, 8, "CALL: name_len");
    const name = new TextDecoder().decode(payload.subarray(7, 7 + nameLen));
    assertEq(name, "prefetch", "CALL: name");
    const args = payload.subarray(7 + nameLen);
    assertEq(args[0], 0x14, "CALL: args op");
    for (let i = 0; i < 16; i++) assertEq(args[1 + i], i + 1, `CALL: id byte ${i}`);
    passed++;
    console.log("  CALL frame: OK");
  }

  // Frame 1: RESULT — request_id=1, flag=success, data=[status_len=2, "ok", write_count=0]
  {
    const { payload, dv: fdv } = readFrame();
    assertEq(payload[0], 0x11, "RESULT: tag");
    assertEq(fdv.getUint32(1, false), 1, "RESULT: request_id");
    assertEq(payload[5], 0x00, "RESULT: flag=success");
    const d = payload.subarray(6);
    const statusLen = new DataView(d.buffer, d.byteOffset).getUint16(0, false);
    assertEq(statusLen, 2, "RESULT: status_len");
    assertEq(new TextDecoder().decode(d.subarray(2, 4)), "ok", "RESULT: status");
    assertEq(d[4], 0, "RESULT: write_count");
    passed++;
    console.log("  RESULT frame: OK");
  }

  // Frame 2: QUERY — request_id=1, query_id=7, sql, mode=query, param=[text, "test_value"]
  {
    const { payload, dv: fdv } = readFrame();
    assertEq(payload[0], 0x12, "QUERY: tag");
    assertEq(fdv.getUint32(1, false), 1, "QUERY: request_id");
    assertEq(fdv.getUint16(5, false), 7, "QUERY: query_id");
    const sqlLen = fdv.getUint16(7, false);
    const sql = new TextDecoder().decode(payload.subarray(9, 9 + sqlLen));
    assertEq(sql, "SELECT id FROM products WHERE id = ?1", "QUERY: sql");
    let p = 9 + sqlLen;
    assertEq(payload[p], 0x00, "QUERY: mode=query"); p++;
    assertEq(payload[p], 1, "QUERY: param_count"); p++;
    assertEq(payload[p], TypeTag.text, "QUERY: param type"); p++;
    const paramLen = new DataView(payload.buffer, payload.byteOffset + p).getUint16(0, false); p += 2;
    assertEq(new TextDecoder().decode(payload.subarray(p, p + paramLen)), "test_value", "QUERY: param value");
    passed++;
    console.log("  QUERY frame: OK");
  }

  // Frame 3: QUERY_RESULT — request_id=1, query_id=7, row_set=[1 col "id" integer, 1 row, value=42]
  {
    const { payload, dv: fdv } = readFrame();
    assertEq(payload[0], 0x13, "QUERY_RESULT: tag");
    assertEq(fdv.getUint32(1, false), 1, "QUERY_RESULT: request_id");
    assertEq(fdv.getUint16(5, false), 7, "QUERY_RESULT: query_id");
    const rsDv = new DataView(payload.buffer, payload.byteOffset + 7, payload.byteLength - 7);
    const { result } = readRowSet(rsDv, 0);
    assertEq(result.columns.length, 1, "QUERY_RESULT: col count");
    assertEq(result.columns[0].name, "id", "QUERY_RESULT: col name");
    assertEq(result.rows.length, 1, "QUERY_RESULT: row count");
    assertEq(result.rows[0].id, 42, "QUERY_RESULT: value");
    passed++;
    console.log("  QUERY_RESULT frame: OK");
  }
}

// =====================================================================
// 3. Constants match enums.json
// =====================================================================
{
  const enumPath = resolve(vectorsDir, "enums.json");
  assert(existsSync(enumPath), "enums.json exists");
  const data = JSON.parse(readFileSync(enumPath, "utf-8"));

  const c = data.constants;
  assertEq(frame_max, c.frame_max, "constant frame_max");
  assertEq(columns_max, c.columns_max, "constant columns_max");
  assertEq(column_name_max, c.column_name_max, "constant column_name_max");
  assertEq(cell_value_max, c.cell_value_max, "constant cell_value_max");

  passed++;
  console.log("  Constants match enums.json: OK");
}

// =====================================================================
// 4. Primitives match primitives.json
// =====================================================================
{
  const primPath = resolve(vectorsDir, "primitives.json");
  assert(existsSync(primPath), "primitives.json exists");
  const p = JSON.parse(readFileSync(primPath, "utf-8"));

  assertEq(TypeTag.integer, p.type_tags.integer, "TypeTag.integer");
  assertEq(TypeTag.float, p.type_tags.float, "TypeTag.float");
  assertEq(TypeTag.text, p.type_tags.text, "TypeTag.text");
  assertEq(TypeTag.blob, p.type_tags.blob, "TypeTag.blob");
  assertEq(TypeTag.null, p.type_tags.null, "TypeTag.null");

  passed++;
  console.log("  Type tags match primitives.json: OK");
}

// =====================================================================
// 5. CRC32 cross-language pair assertion
// =====================================================================
// Validates Node.js zlib.crc32 matches committed vectors (which are
// generated by Zig's std.hash.crc.Crc32). The C addon has its own
// self-test (verify_crc_table at init). This test closes the triangle:
// Zig generates vectors → TS validates vectors → C self-tests at load.
{
  const { crc32 } = await import("node:zlib");
  const crcPath = resolve(vectorsDir, "crc_vectors.json");
  assert(existsSync(crcPath), "crc_vectors.json exists");
  const vectors: Array<{ description: string; input_hex: string; expected_crc32: number }> =
    JSON.parse(readFileSync(crcPath, "utf-8"));

  for (const v of vectors) {
    const input = Buffer.from(v.input_hex, "hex");
    const actual = crc32(input);
    assertEq(actual, v.expected_crc32, `CRC32 vector: ${v.description}`);
  }
  passed++;
  console.log("  CRC32 vectors match Node.js zlib: OK");
}

console.log(`\nAll ${passed} protocol vector tests passed.`);
