var data = {lines:[
{"lineNum":"    1","line":"const std = @import(\"std\");"},
{"lineNum":"    2","line":"const t = @import(\"../prelude.zig\");"},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"pub const Status = enum { ok, not_found };"},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"pub const Prefetch = struct {"},
{"lineNum":"    7","line":"    collection_id: u128,"},
{"lineNum":"    8","line":"    product_id: u128,"},
{"lineNum":"    9","line":"    collection: ?t.CollectionRow,"},
{"lineNum":"   10","line":"    product: ?t.ProductRow,"},
{"lineNum":"   11","line":"};"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"pub const Context = t.HandlerContext(Prefetch, t.Operation.EventType(.add_collection_member), t.Identity, Status);"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"// [route] .add_collection_member"},
{"lineNum":"   16","line":"// match POST /collections/:id/products/:sub_id"},
{"lineNum":"   17","line":"pub fn route(params: t.RouteParams, body: []const u8) ?t.Message {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   18","line":"    _ = body;"},
{"lineNum":"   19","line":"    const id = t.stdx.parse_uuid(params.get(\"id\") orelse return null) orelse return null;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   20","line":"    const sub_id = t.stdx.parse_uuid(params.get(\"sub_id\") orelse return null) orelse return null;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   21","line":"    return t.Message.init(.add_collection_member, id, 0, sub_id);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   22","line":"}"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"// [prefetch] .add_collection_member"},
{"lineNum":"   25","line":"pub fn prefetch(storage: anytype, msg: *const t.Message) ?Prefetch {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   26","line":"    const product_id = msg.body_as(u128).*;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   27","line":"    return .{","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   28","line":"        .collection_id = msg.id,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   29","line":"        .product_id = product_id,"},
{"lineNum":"   30","line":"        .collection = storage.query(t.CollectionRow,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   31","line":"            \"SELECT id, name, active FROM collections WHERE id = ?1;\", .{msg.id}),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   32","line":"        .product = storage.query(t.ProductRow,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   33","line":"            \"SELECT id, name, description, price_cents, inventory, version, active FROM products WHERE id = ?1;\","},
{"lineNum":"   34","line":"            .{product_id}),"},
{"lineNum":"   35","line":"    };"},
{"lineNum":"   36","line":"}"},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"// [handle] .add_collection_member"},
{"lineNum":"   39","line":"pub fn handle(ctx: Context, db: anytype) t.HandleResult {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   40","line":"    _ = ctx.prefetched.collection orelse","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   41","line":"        return .{ .status = .not_found };","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   42","line":"    _ = ctx.prefetched.product orelse","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   43","line":"        return .{ .status = .not_found };","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   44","line":"    db.execute(","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   45","line":"        t.sql.collection_members.upsert,"},
{"lineNum":"   46","line":"        .{ ctx.prefetched.collection_id, ctx.prefetched.product_id },","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   47","line":"    );"},
{"lineNum":"   48","line":"    return .{};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   49","line":"}"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"// [render] .add_collection_member"},
{"lineNum":"   52","line":"pub fn render(ctx: Context) []const u8 {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   53","line":"    return switch (ctx.status) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   54","line":"        .ok => \"\","},
{"lineNum":"   55","line":"        .not_found => \"<div class=\\\"error\\\">Collection or product not found</div>\","},
{"lineNum":"   56","line":"    };"},
{"lineNum":"   57","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2026-04-01 10:26:58", "instrumented" : 21, "covered" : 0,};
var merged_data = [];
