// Focus codegen — reads the annotation manifest from the scanner,
// extracts handler module info, and generates handlers.generated.ts.
//
// Library function — called by bin/focus-codegen.ts.
// Generates: handler imports, modules registry, route table,
// prefetch key map, OperationValues, worker functions.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

export interface CodegenArgs {
  manifestPath: string;
  outputPath: string;
  opsRegistryPath?: string;
  opsOutputPath?: string;
}

export function runCodegen(args: CodegenArgs): void {

const { manifestPath, outputPath, opsRegistryPath, opsOutputPath } = args;

interface ManifestAnnotation {
  phase: "translate" | "prefetch" | "execute" | "render" | "worker";
  operation: string;
  file: string;
  has_body?: boolean;
  route_match?: { method: string; pattern: string; query_params?: string[] };
  returns?: string;
}

// Read manifest.
const manifest: { annotations: ManifestAnnotation[] } = JSON.parse(
  readFileSync(manifestPath, "utf-8")
);

// Build per-operation module map: operation → { file, namespace }.
const operationModules = new Map<string, { file: string; namespace: string }>();

function toCamelCase(op: string): string {
  return op.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

for (const ann of manifest.annotations) {
  if (!operationModules.has(ann.operation)) {
    operationModules.set(ann.operation, {
      file: ann.file,
      namespace: toCamelCase(ann.operation),
    });
  }
}

// Build route table from match directives.
interface RouteEntry { operation: string; method: string; pattern: string; query_params: string[]; }
const routeTable: RouteEntry[] = [];
for (const ann of manifest.annotations) {
  if (ann.phase === "translate" && ann.route_match) {
    routeTable.push({
      operation: ann.operation,
      method: ann.route_match.method,
      pattern: ann.route_match.pattern,
      query_params: ann.route_match.query_params || [],
    });
  }
}

// Sort routes by specificity.
function routeSpecificity(pattern: string): number[] {
  if (pattern === "/") return [0];
  return pattern.slice(1).split("/").map(seg =>
    seg.startsWith(":") ? 0 : 1
  );
}

routeTable.sort((a, b) => {
  if (a.method !== b.method) return a.method < b.method ? -1 : 1;
  const specA = routeSpecificity(a.pattern);
  const specB = routeSpecificity(b.pattern);
  if (specA.length !== specB.length) return specB.length - specA.length;
  for (let i = 0; i < specA.length; i++) {
    if (specA[i] !== specB[i]) return specB[i] - specA[i];
  }
  return a.operation < b.operation ? -1 : 1;
});

// Generate output.
let out = `// Auto-generated by the TypeScript adapter — do not edit.
//
// Handler imports, modules registry, and route table for the
// CALL/RESULT sidecar runtime. Generated from the annotation
// scanner's manifest.json.

`;

// Namespace imports — compute paths relative to output file location.
const outputDir = dirname(resolve(outputPath));
for (const [_op, mod] of operationModules) {
  const absHandler = resolve(mod.file);
  let rel = relative(outputDir, absHandler);
  if (!rel.startsWith(".")) rel = "./" + rel;
  out += `import * as ${mod.namespace} from '${rel}';\n`;
}

out += `
export interface HandlerModule {
  route?: (req: any) => any | null;
  prefetch?: (msg: any, db: any) => any;
  handle?: (ctx: any, db: any) => string;
  render?: (ctx: any, db?: any) => string;
}

export const modules: Record<string, HandlerModule> = {\n`;
for (const [op, mod] of operationModules) {
  out += `  ${op}: ${mod.namespace},\n`;
}
out += `};

export interface RouteTableEntry {
  operation: string;
  method: string;
  pattern: string;
  query_params: string[];
}

export const routeTable: RouteTableEntry[] = [\n`;
for (const r of routeTable) {
  const qp = r.query_params.length > 0
    ? `[${r.query_params.map((q: string) => `'${q}'`).join(', ')}]`
    : `[]`;
  out += `  { operation: '${r.operation}', method: '${r.method}', pattern: '${r.pattern}', query_params: ${qp} },\n`;
}
out += `];\n`;

// Prefetch key map — extracted from handler source at build time.
// Replaces the runtime fn.toString() hack in call_runtime_shm.ts.
//
// The annotation marker `// [prefetch] .<operation>` is stable under
// unrelated edits in the file, unlike a line number. We locate the
// function body by searching for the marker and slicing from there.
interface PrefetchKeyInfo { key: string; mode: "query" | "queryAll"; }
const prefetchKeyMapData: Record<string, PrefetchKeyInfo[]> = {};
for (const ann of manifest.annotations) {
  if (ann.phase !== "prefetch" || !ann.has_body) continue;
  try {
    const src = readFileSync(ann.file, "utf-8");
    const marker = `// [prefetch] .${ann.operation}`;
    const markerIdx = src.indexOf(marker);
    if (markerIdx < 0) continue;
    const bodyLines = src.slice(markerIdx);
    const infos: PrefetchKeyInfo[] = [];
    const callRe = /db\.(query|queryAll)\s*\(/g;
    let cm;
    while ((cm = callRe.exec(bodyLines)) !== null) {
      infos.push({ key: "", mode: cm[1] === "query" ? "query" : "queryAll" });
    }
    const m = bodyLines.match(/return\s*(?:\{|\(\s*\{)\s*([^}]+)\}/);
    if (m) {
      const parts = m[1].split(",").map((p: string) => p.split(":")[0].trim()).filter(Boolean);
      for (let i = 0; i < Math.min(parts.length, infos.length); i++) {
        infos[i].key = parts[i];
      }
    }
    if (infos.length > 0 && infos[0].key) prefetchKeyMapData[ann.operation] = infos;
  } catch { /* Skip files that can't be read. */ }
}

// Generate OperationValues from operations.json — ensures new operations
// are available to the sidecar runtime without hand-editing types.generated.ts.
let opsJson: Record<string, number> = {};
if (opsRegistryPath) {
  try { opsJson = JSON.parse(readFileSync(opsRegistryPath, "utf-8")); } catch { /* no ops registry */ }
} else {
  // Fallback: look next to manifest, then next to output.
  try { opsJson = JSON.parse(readFileSync(resolve(dirname(resolve(manifestPath)), "operations.json"), "utf-8")); } catch {
    try { opsJson = JSON.parse(readFileSync(resolve(dirname(resolve(outputPath)), "operations.json"), "utf-8")); } catch { /* no ops registry */ }
  }
}

// Generate Operation type union from operations.json — gives IDE type
// checking for new operations without hand-editing types.generated.ts.
const opNames = Object.keys(opsJson).filter(k => k !== "root");
const opType = opNames.length > 0
  ? opNames.map(n => `"${n}"`).join(" | ")
  : "string";

out += `
export interface PrefetchKeyInfo { key: string; mode: "query" | "queryAll"; }
export const prefetchKeyMap: Record<string, PrefetchKeyInfo[]> = ${JSON.stringify(prefetchKeyMapData)};

// Generated from operations.json — always includes new operations.
export const OperationValues: Record<string, number> = ${JSON.stringify(opsJson)};
export type Operation = ${opType};
`;

// Worker functions — one entry per [worker] annotation.
const workerAnnotations = manifest.annotations.filter(a => a.phase === "worker");
if (workerAnnotations.length > 0) {
  // Ensure worker modules are imported.
  for (const ann of workerAnnotations) {
    if (!operationModules.has(ann.operation)) {
      operationModules.set(ann.operation, {
        file: ann.file,
        namespace: toCamelCase(ann.operation),
      });
      const relative = "../" + ann.file;
      // Import already emitted above if the file has other phases.
      // Check if we need to add it.
      if (!out.includes(`import * as ${toCamelCase(ann.operation)}`)) {
        // Prepend import (insert after the first newline in the generated section).
        const importLine = `import * as ${toCamelCase(ann.operation)} from '${relative}';\n`;
        const insertPos = out.indexOf('\n') + 1;
        out = out.slice(0, insertPos) + importLine + out.slice(insertPos);
      }
    }
  }

  out += `
export interface WorkerFunction {
  fn: (...args: any[]) => Promise<any>;
  returns: string;
}

export const workerFunctions: Record<string, WorkerFunction> = {\n`;
  for (const ann of workerAnnotations) {
    const ns = toCamelCase(ann.operation);
    out += `  ${ann.operation}: { fn: ${ns}.${ann.operation}, returns: '${ann.returns || ''}' },\n`;
  }
  out += `};\n`;
}

writeFileSync(outputPath, out);
console.log(`Generated: ${outputPath}`);

// Generate operations.ts as a separate file (if output path given).
// This replaces the inline node -e in focus-internal.
if (opsOutputPath && Object.keys(opsJson).length > 0) {
  const opNames = Object.keys(opsJson).filter(k => k !== "root");
  const opUnion = opNames.length > 0
    ? opNames.map(n => `"${n}"`).join(" | ")
    : "string";
  const opsOut =
    `// Generated from operations.json — do not edit.\n` +
    `export type Operation = ${opUnion};\n` +
    `export const OperationValues: Record<string, number> = ${JSON.stringify(opsJson)};\n`;
  writeFileSync(opsOutputPath, opsOut);
  console.log(`Generated: ${opsOutputPath}`);
}

} // end runCodegen
